/**
 * Drift detection tests — ensure ElectroDB entity attribute definitions stay
 * in sync with the Zod schemas defined in `lib/db/schemas.ts`.
 *
 * These tests block deployments when someone updates one definition but forgets
 * to update the other.  The type guards in `lib/db/type-guards.ts` provide the
 * corresponding compile-time (IDE) safety.
 */

import { describe, it } from "bun:test";
import { AuthVerificationEntity, BusEntity, CmsUserEntity, EventEntity, LocationEntity, MediaEntity, MemberEntity, NewsEntity, SponsorEntity, TeamEntity } from "./electrodb-entities";
import { authVerificationSchema, busSchema, cmsUserSchema, eventSchema, locationSchema, mediaSchema, memberSchema, newsSchema, sponsorSchema, teamSchema } from "./schemas";

/** Extract sorted top-level attribute names from an ElectroDB entity schema */
function getEntityAttributeNames(entity: { schema: { attributes: Record<string, unknown> } }): string[] {
	return Object.keys(entity.schema.attributes).sort();
}

/** Extract sorted top-level field names from a Zod object schema */
function getZodFieldNames(schema: { _def: { shape: Record<string, unknown> } }): string[] {
	return Object.keys(schema._def.shape).sort();
}

/**
 * Assert that every top-level field in the Zod schema has a corresponding
 * attribute in the ElectroDB entity.
 *
 * ElectroDB entities may include additional internal fields (pk, sk, gsi1pk…)
 * that are NOT in the Zod schema — those are allowed.  What we enforce is that
 * no Zod field is silently missing from the ElectroDB definition.
 */
function assertNoMissingAttributes(entityName: string, zodFields: string[], electroFields: string[]): void {
	const electroSet = new Set(electroFields);
	const missing = zodFields.filter((f) => !electroSet.has(f));
	if (missing.length > 0) {
		throw new Error(`[${entityName}] Zod fields missing from ElectroDB entity: ${missing.join(", ")}.\n` + "Add the attribute(s) to the ElectroDB entity in lib/db/electrodb-entities.ts.");
	}
}

/**
 * Assert that every ElectroDB attribute (excluding generated key fields) has a
 * corresponding field in the Zod schema, preventing stale ElectroDB-only fields.
 */
function assertNoSurplusAttributes(
	entityName: string,
	zodFields: string[],
	electroFields: string[],
	/** Key fields generated by ElectroDB that have no Zod equivalent */
	generatedKeyFields: string[],
): void {
	const zodSet = new Set(zodFields);
	const keySet = new Set(generatedKeyFields);
	const surplus = electroFields.filter((f) => !zodSet.has(f) && !keySet.has(f));
	if (surplus.length > 0) {
		throw new Error(
			`[${entityName}] ElectroDB attributes without a matching Zod field: ${surplus.join(", ")}.\n` +
				"Either add the field to the Zod schema in lib/db/schemas.ts or remove it from the ElectroDB entity.",
		);
	}
}

/** Key fields that ElectroDB injects and are not part of the Zod schema */
const GENERATED_KEY_FIELDS = ["pk", "sk", "gsi1pk", "gsi1sk", "gsi2pk", "gsi2sk", "gsi3pk", "gsi3sk", "gsi4pk", "gsi4sk", "__edb_e__", "__edb_v__"];

function checkDrift(entityName: string, zodSchema: Parameters<typeof getZodFieldNames>[0], entity: Parameters<typeof getEntityAttributeNames>[0]): void {
	const zodFields = getZodFieldNames(zodSchema);
	const electroFields = getEntityAttributeNames(entity);
	assertNoMissingAttributes(entityName, zodFields, electroFields);
	assertNoSurplusAttributes(entityName, zodFields, electroFields, GENERATED_KEY_FIELDS);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("ElectroDB ↔ Zod drift detection", () => {
	it("News entity attributes match newsSchema", () => {
		checkDrift("News", newsSchema, NewsEntity);
	});

	it("Event entity attributes match eventSchema", () => {
		checkDrift("Event", eventSchema, EventEntity);
	});

	it("Team entity attributes match teamSchema", () => {
		checkDrift("Team", teamSchema, TeamEntity);
	});

	it("Member entity attributes match memberSchema", () => {
		checkDrift("Member", memberSchema, MemberEntity);
	});

	it("Media entity attributes match mediaSchema", () => {
		checkDrift("Media", mediaSchema, MediaEntity);
	});

	it("Sponsor entity attributes match sponsorSchema", () => {
		checkDrift("Sponsor", sponsorSchema, SponsorEntity);
	});

	it("Location entity attributes match locationSchema", () => {
		checkDrift("Location", locationSchema, LocationEntity);
	});

	it("Bus entity attributes match busSchema", () => {
		checkDrift("Bus", busSchema, BusEntity);
	});

	it("CmsUser entity attributes match cmsUserSchema", () => {
		checkDrift("CmsUser", cmsUserSchema, CmsUserEntity);
	});

	it("AuthVerification entity attributes match authVerificationSchema", () => {
		checkDrift("AuthVerification", authVerificationSchema, AuthVerificationEntity);
	});
});
