/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AdminOtpLoginRouteImport } from './routes/admin/otp-login'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as LayoutTermineRouteImport } from './routes/_layout/termine'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutTabelleRouteImport } from './routes/_layout/tabelle'
import { Route as LayoutSatzungRouteImport } from './routes/_layout/satzung'
import { Route as LayoutNewsRouteImport } from './routes/_layout/news'
import { Route as LayoutJugendschutzRouteImport } from './routes/_layout/jugendschutz'
import { Route as LayoutImpressumRouteImport } from './routes/_layout/impressum'
import { Route as LayoutFotosRouteImport } from './routes/_layout/fotos'
import { Route as LayoutDatenschutzRouteImport } from './routes/_layout/datenschutz'
import { Route as LayoutBusRouteImport } from './routes/_layout/bus'
import { Route as LayoutBrandRouteImport } from './routes/_layout/brand'
import { Route as LayoutBeitragsordnungRouteImport } from './routes/_layout/beitragsordnung'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as LayoutTermineIndexRouteImport } from './routes/_layout/termine.index'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams.index'
import { Route as LayoutNewsIndexRouteImport } from './routes/_layout/news.index'
import { Route as ApiSamsLogosRouteImport } from './routes/api/sams/logos'
import { Route as ApiIcsTeamSlugRouteImport } from './routes/api/ics/$teamSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutTeamsRouteImport } from './routes/admin/_layout/teams'
import { Route as AdminLayoutSponsorsRouteImport } from './routes/admin/_layout/sponsors'
import { Route as AdminLayoutSamsRouteImport } from './routes/admin/_layout/sams'
import { Route as AdminLayoutNewsRouteImport } from './routes/admin/_layout/news'
import { Route as AdminLayoutMembersRouteImport } from './routes/admin/_layout/members'
import { Route as AdminLayoutLocationsRouteImport } from './routes/admin/_layout/locations'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout/events'
import { Route as AdminLayoutBusRouteImport } from './routes/admin/_layout/bus'
import { Route as LayoutTermineIdRouteImport } from './routes/_layout/termine.$id'
import { Route as LayoutTeamsSlugRouteImport } from './routes/_layout/teams.$slug'
import { Route as LayoutNewsIdRouteImport } from './routes/_layout/news.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminOtpLoginRoute = AdminOtpLoginRouteImport.update({
  id: '/admin/otp-login',
  path: '/admin/otp-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTermineRoute = LayoutTermineRouteImport.update({
  id: '/termine',
  path: '/termine',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTabelleRoute = LayoutTabelleRouteImport.update({
  id: '/tabelle',
  path: '/tabelle',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSatzungRoute = LayoutSatzungRouteImport.update({
  id: '/satzung',
  path: '/satzung',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewsRoute = LayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJugendschutzRoute = LayoutJugendschutzRouteImport.update({
  id: '/jugendschutz',
  path: '/jugendschutz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImpressumRoute = LayoutImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFotosRoute = LayoutFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatenschutzRoute = LayoutDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBusRoute = LayoutBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandRoute = LayoutBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBeitragsordnungRoute = LayoutBeitragsordnungRouteImport.update({
  id: '/beitragsordnung',
  path: '/beitragsordnung',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LayoutTermineIndexRoute = LayoutTermineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTermineRoute,
} as any)
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutNewsIndexRoute = LayoutNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutNewsRoute,
} as any)
const ApiSamsLogosRoute = ApiSamsLogosRouteImport.update({
  id: '/api/sams/logos',
  path: '/api/sams/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIcsTeamSlugRoute = ApiIcsTeamSlugRouteImport.update({
  id: '/api/ics/$teamSlug',
  path: '/api/ics/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTeamsRoute = AdminLayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSponsorsRoute = AdminLayoutSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSamsRoute = AdminLayoutSamsRouteImport.update({
  id: '/sams',
  path: '/sams',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutNewsRoute = AdminLayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMembersRoute = AdminLayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLocationsRoute = AdminLayoutLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBusRoute = AdminLayoutBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LayoutTermineIdRoute = LayoutTermineIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutTermineRoute,
} as any)
const LayoutTeamsSlugRoute = LayoutTeamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutNewsIdRoute = LayoutNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/beitragsordnung': typeof LayoutBeitragsordnungRoute
  '/brand': typeof LayoutBrandRoute
  '/bus': typeof LayoutBusRoute
  '/datenschutz': typeof LayoutDatenschutzRoute
  '/fotos': typeof LayoutFotosRoute
  '/impressum': typeof LayoutImpressumRoute
  '/jugendschutz': typeof LayoutJugendschutzRoute
  '/news': typeof LayoutNewsRouteWithChildren
  '/satzung': typeof LayoutSatzungRoute
  '/tabelle': typeof LayoutTabelleRoute
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/termine': typeof LayoutTermineRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/news/$id': typeof LayoutNewsIdRoute
  '/teams/$slug': typeof LayoutTeamsSlugRoute
  '/termine/$id': typeof LayoutTermineIdRoute
  '/admin/bus': typeof AdminLayoutBusRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/locations': typeof AdminLayoutLocationsRoute
  '/admin/members': typeof AdminLayoutMembersRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/sams': typeof AdminLayoutSamsRoute
  '/admin/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/teams': typeof AdminLayoutTeamsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ics/$teamSlug': typeof ApiIcsTeamSlugRoute
  '/api/sams/logos': typeof ApiSamsLogosRoute
  '/news/': typeof LayoutNewsIndexRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/termine/': typeof LayoutTermineIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/beitragsordnung': typeof LayoutBeitragsordnungRoute
  '/brand': typeof LayoutBrandRoute
  '/bus': typeof LayoutBusRoute
  '/datenschutz': typeof LayoutDatenschutzRoute
  '/fotos': typeof LayoutFotosRoute
  '/impressum': typeof LayoutImpressumRoute
  '/jugendschutz': typeof LayoutJugendschutzRoute
  '/satzung': typeof LayoutSatzungRoute
  '/tabelle': typeof LayoutTabelleRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/': typeof LayoutIndexRoute
  '/news/$id': typeof LayoutNewsIdRoute
  '/teams/$slug': typeof LayoutTeamsSlugRoute
  '/termine/$id': typeof LayoutTermineIdRoute
  '/admin/bus': typeof AdminLayoutBusRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/locations': typeof AdminLayoutLocationsRoute
  '/admin/members': typeof AdminLayoutMembersRoute
  '/admin/news': typeof AdminLayoutNewsRoute
  '/admin/sams': typeof AdminLayoutSamsRoute
  '/admin/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/teams': typeof AdminLayoutTeamsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ics/$teamSlug': typeof ApiIcsTeamSlugRoute
  '/api/sams/logos': typeof ApiSamsLogosRoute
  '/news': typeof LayoutNewsIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/termine': typeof LayoutTermineIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/beitragsordnung': typeof LayoutBeitragsordnungRoute
  '/_layout/brand': typeof LayoutBrandRoute
  '/_layout/bus': typeof LayoutBusRoute
  '/_layout/datenschutz': typeof LayoutDatenschutzRoute
  '/_layout/fotos': typeof LayoutFotosRoute
  '/_layout/impressum': typeof LayoutImpressumRoute
  '/_layout/jugendschutz': typeof LayoutJugendschutzRoute
  '/_layout/news': typeof LayoutNewsRouteWithChildren
  '/_layout/satzung': typeof LayoutSatzungRoute
  '/_layout/tabelle': typeof LayoutTabelleRoute
  '/_layout/teams': typeof LayoutTeamsRouteWithChildren
  '/_layout/termine': typeof LayoutTermineRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/otp-login': typeof AdminOtpLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/news/$id': typeof LayoutNewsIdRoute
  '/_layout/teams/$slug': typeof LayoutTeamsSlugRoute
  '/_layout/termine/$id': typeof LayoutTermineIdRoute
  '/admin/_layout/bus': typeof AdminLayoutBusRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/locations': typeof AdminLayoutLocationsRoute
  '/admin/_layout/members': typeof AdminLayoutMembersRoute
  '/admin/_layout/news': typeof AdminLayoutNewsRoute
  '/admin/_layout/sams': typeof AdminLayoutSamsRoute
  '/admin/_layout/sponsors': typeof AdminLayoutSponsorsRoute
  '/admin/_layout/teams': typeof AdminLayoutTeamsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ics/$teamSlug': typeof ApiIcsTeamSlugRoute
  '/api/sams/logos': typeof ApiSamsLogosRoute
  '/_layout/news/': typeof LayoutNewsIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/termine/': typeof LayoutTermineIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beitragsordnung'
    | '/brand'
    | '/bus'
    | '/datenschutz'
    | '/fotos'
    | '/impressum'
    | '/jugendschutz'
    | '/news'
    | '/satzung'
    | '/tabelle'
    | '/teams'
    | '/termine'
    | '/admin'
    | '/admin/login'
    | '/admin/otp-login'
    | '/news/$id'
    | '/teams/$slug'
    | '/termine/$id'
    | '/admin/bus'
    | '/admin/events'
    | '/admin/locations'
    | '/admin/members'
    | '/admin/news'
    | '/admin/sams'
    | '/admin/sponsors'
    | '/admin/teams'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/ics/$teamSlug'
    | '/api/sams/logos'
    | '/news/'
    | '/teams/'
    | '/termine/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/beitragsordnung'
    | '/brand'
    | '/bus'
    | '/datenschutz'
    | '/fotos'
    | '/impressum'
    | '/jugendschutz'
    | '/satzung'
    | '/tabelle'
    | '/admin/login'
    | '/admin/otp-login'
    | '/'
    | '/news/$id'
    | '/teams/$slug'
    | '/termine/$id'
    | '/admin/bus'
    | '/admin/events'
    | '/admin/locations'
    | '/admin/members'
    | '/admin/news'
    | '/admin/sams'
    | '/admin/sponsors'
    | '/admin/teams'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/ics/$teamSlug'
    | '/api/sams/logos'
    | '/news'
    | '/teams'
    | '/termine'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/beitragsordnung'
    | '/_layout/brand'
    | '/_layout/bus'
    | '/_layout/datenschutz'
    | '/_layout/fotos'
    | '/_layout/impressum'
    | '/_layout/jugendschutz'
    | '/_layout/news'
    | '/_layout/satzung'
    | '/_layout/tabelle'
    | '/_layout/teams'
    | '/_layout/termine'
    | '/admin/_layout'
    | '/admin/login'
    | '/admin/otp-login'
    | '/_layout/'
    | '/_layout/news/$id'
    | '/_layout/teams/$slug'
    | '/_layout/termine/$id'
    | '/admin/_layout/bus'
    | '/admin/_layout/events'
    | '/admin/_layout/locations'
    | '/admin/_layout/members'
    | '/admin/_layout/news'
    | '/admin/_layout/sams'
    | '/admin/_layout/sponsors'
    | '/admin/_layout/teams'
    | '/admin/_layout/users'
    | '/api/auth/$'
    | '/api/ics/$teamSlug'
    | '/api/sams/logos'
    | '/_layout/news/'
    | '/_layout/teams/'
    | '/_layout/termine/'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOtpLoginRoute: typeof AdminOtpLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIcsTeamSlugRoute: typeof ApiIcsTeamSlugRoute
  ApiSamsLogosRoute: typeof ApiSamsLogosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/otp-login': {
      id: '/admin/otp-login'
      path: '/admin/otp-login'
      fullPath: '/admin/otp-login'
      preLoaderRoute: typeof AdminOtpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/termine': {
      id: '/_layout/termine'
      path: '/termine'
      fullPath: '/termine'
      preLoaderRoute: typeof LayoutTermineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tabelle': {
      id: '/_layout/tabelle'
      path: '/tabelle'
      fullPath: '/tabelle'
      preLoaderRoute: typeof LayoutTabelleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/satzung': {
      id: '/_layout/satzung'
      path: '/satzung'
      fullPath: '/satzung'
      preLoaderRoute: typeof LayoutSatzungRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/news': {
      id: '/_layout/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof LayoutNewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jugendschutz': {
      id: '/_layout/jugendschutz'
      path: '/jugendschutz'
      fullPath: '/jugendschutz'
      preLoaderRoute: typeof LayoutJugendschutzRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/impressum': {
      id: '/_layout/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof LayoutImpressumRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fotos': {
      id: '/_layout/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof LayoutFotosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datenschutz': {
      id: '/_layout/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof LayoutDatenschutzRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bus': {
      id: '/_layout/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof LayoutBusRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brand': {
      id: '/_layout/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof LayoutBrandRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/beitragsordnung': {
      id: '/_layout/beitragsordnung'
      path: '/beitragsordnung'
      fullPath: '/beitragsordnung'
      preLoaderRoute: typeof LayoutBeitragsordnungRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_layout/termine/': {
      id: '/_layout/termine/'
      path: '/'
      fullPath: '/termine/'
      preLoaderRoute: typeof LayoutTermineIndexRouteImport
      parentRoute: typeof LayoutTermineRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/news/': {
      id: '/_layout/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof LayoutNewsIndexRouteImport
      parentRoute: typeof LayoutNewsRoute
    }
    '/api/sams/logos': {
      id: '/api/sams/logos'
      path: '/api/sams/logos'
      fullPath: '/api/sams/logos'
      preLoaderRoute: typeof ApiSamsLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ics/$teamSlug': {
      id: '/api/ics/$teamSlug'
      path: '/api/ics/$teamSlug'
      fullPath: '/api/ics/$teamSlug'
      preLoaderRoute: typeof ApiIcsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/teams': {
      id: '/admin/_layout/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminLayoutTeamsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/sponsors': {
      id: '/admin/_layout/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminLayoutSponsorsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/sams': {
      id: '/admin/_layout/sams'
      path: '/sams'
      fullPath: '/admin/sams'
      preLoaderRoute: typeof AdminLayoutSamsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/news': {
      id: '/admin/_layout/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminLayoutNewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/members': {
      id: '/admin/_layout/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminLayoutMembersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/locations': {
      id: '/admin/_layout/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLayoutLocationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bus': {
      id: '/admin/_layout/bus'
      path: '/bus'
      fullPath: '/admin/bus'
      preLoaderRoute: typeof AdminLayoutBusRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_layout/termine/$id': {
      id: '/_layout/termine/$id'
      path: '/$id'
      fullPath: '/termine/$id'
      preLoaderRoute: typeof LayoutTermineIdRouteImport
      parentRoute: typeof LayoutTermineRoute
    }
    '/_layout/teams/$slug': {
      id: '/_layout/teams/$slug'
      path: '/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof LayoutTeamsSlugRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/news/$id': {
      id: '/_layout/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof LayoutNewsIdRouteImport
      parentRoute: typeof LayoutNewsRoute
    }
  }
}

interface LayoutNewsRouteChildren {
  LayoutNewsIdRoute: typeof LayoutNewsIdRoute
  LayoutNewsIndexRoute: typeof LayoutNewsIndexRoute
}

const LayoutNewsRouteChildren: LayoutNewsRouteChildren = {
  LayoutNewsIdRoute: LayoutNewsIdRoute,
  LayoutNewsIndexRoute: LayoutNewsIndexRoute,
}

const LayoutNewsRouteWithChildren = LayoutNewsRoute._addFileChildren(
  LayoutNewsRouteChildren,
)

interface LayoutTeamsRouteChildren {
  LayoutTeamsSlugRoute: typeof LayoutTeamsSlugRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
}

const LayoutTeamsRouteChildren: LayoutTeamsRouteChildren = {
  LayoutTeamsSlugRoute: LayoutTeamsSlugRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
}

const LayoutTeamsRouteWithChildren = LayoutTeamsRoute._addFileChildren(
  LayoutTeamsRouteChildren,
)

interface LayoutTermineRouteChildren {
  LayoutTermineIdRoute: typeof LayoutTermineIdRoute
  LayoutTermineIndexRoute: typeof LayoutTermineIndexRoute
}

const LayoutTermineRouteChildren: LayoutTermineRouteChildren = {
  LayoutTermineIdRoute: LayoutTermineIdRoute,
  LayoutTermineIndexRoute: LayoutTermineIndexRoute,
}

const LayoutTermineRouteWithChildren = LayoutTermineRoute._addFileChildren(
  LayoutTermineRouteChildren,
)

interface LayoutRouteChildren {
  LayoutBeitragsordnungRoute: typeof LayoutBeitragsordnungRoute
  LayoutBrandRoute: typeof LayoutBrandRoute
  LayoutBusRoute: typeof LayoutBusRoute
  LayoutDatenschutzRoute: typeof LayoutDatenschutzRoute
  LayoutFotosRoute: typeof LayoutFotosRoute
  LayoutImpressumRoute: typeof LayoutImpressumRoute
  LayoutJugendschutzRoute: typeof LayoutJugendschutzRoute
  LayoutNewsRoute: typeof LayoutNewsRouteWithChildren
  LayoutSatzungRoute: typeof LayoutSatzungRoute
  LayoutTabelleRoute: typeof LayoutTabelleRoute
  LayoutTeamsRoute: typeof LayoutTeamsRouteWithChildren
  LayoutTermineRoute: typeof LayoutTermineRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBeitragsordnungRoute: LayoutBeitragsordnungRoute,
  LayoutBrandRoute: LayoutBrandRoute,
  LayoutBusRoute: LayoutBusRoute,
  LayoutDatenschutzRoute: LayoutDatenschutzRoute,
  LayoutFotosRoute: LayoutFotosRoute,
  LayoutImpressumRoute: LayoutImpressumRoute,
  LayoutJugendschutzRoute: LayoutJugendschutzRoute,
  LayoutNewsRoute: LayoutNewsRouteWithChildren,
  LayoutSatzungRoute: LayoutSatzungRoute,
  LayoutTabelleRoute: LayoutTabelleRoute,
  LayoutTeamsRoute: LayoutTeamsRouteWithChildren,
  LayoutTermineRoute: LayoutTermineRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutBusRoute: typeof AdminLayoutBusRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutLocationsRoute: typeof AdminLayoutLocationsRoute
  AdminLayoutMembersRoute: typeof AdminLayoutMembersRoute
  AdminLayoutNewsRoute: typeof AdminLayoutNewsRoute
  AdminLayoutSamsRoute: typeof AdminLayoutSamsRoute
  AdminLayoutSponsorsRoute: typeof AdminLayoutSponsorsRoute
  AdminLayoutTeamsRoute: typeof AdminLayoutTeamsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutBusRoute: AdminLayoutBusRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutLocationsRoute: AdminLayoutLocationsRoute,
  AdminLayoutMembersRoute: AdminLayoutMembersRoute,
  AdminLayoutNewsRoute: AdminLayoutNewsRoute,
  AdminLayoutSamsRoute: AdminLayoutSamsRoute,
  AdminLayoutSponsorsRoute: AdminLayoutSponsorsRoute,
  AdminLayoutTeamsRoute: AdminLayoutTeamsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminOtpLoginRoute: AdminOtpLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIcsTeamSlugRoute: ApiIcsTeamSlugRoute,
  ApiSamsLogosRoute: ApiSamsLogosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
