name: "VC M端llheim e.V."
short_name: "VCM"
title: "Volleyball Club M端llheim"
description: "In M端llheim geh es in Sachen Volleyball richtig ab! Von Freizeit Team bis zur Verbandsliga. Hier findest du alle Infos und Neuigkeiten des Vereins."
logo: '/img/logo.png'
favicon: '/img/favicon.png'
apple_touch_icon: '/img/apple-touch-icon.png'
apple_touch_startup_image: '/img/vcm-banner-white.png'
language: 'de'
language_direction: 'ltr'
theme_color: "#363b40"
background_color: "#366273"
include: ["_pages"]
permalink: /:title/
url: https://vcmuellheim.de
author: "VC M端llheim"

# Jekyll GitHub Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

## Add Club Members to show on a contacts page
collections:
  club_members:
    people: true
  teams:
    sort_by: liga
