name: "VC Müllheim e.V."
title: "Volleyball Club Müllheim e.V."
description: "In Müllheim geh es in Sachen Volleyball richtig ab! Von Freizeit Team bis zur Verbandsliga. Hier findest du alle Infos und Neuigkeiten des Vereins."
logo: '/img/logo.png'
favicon: '/img/logo.png'
google_analytics: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Jekyll GitHub Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://vcmuellheim.de


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


## Add Club Members to show on a contacts page
collections:
  club_members:
    people: true
