name: "VC Müllheim"
short_name: "VCM"
official_name: "Volleyballclub Müllheim e.V."
title: "Volleyball Club Müllheim"
description: "In Müllheim geh es in Sachen Volleyball richtig ab! Von Freizeit Team bis zur Verbandsliga. Hier findest du alle Infos und Neuigkeiten des Vereins."
logo: "/img/logo.png"
favicon: "/img/favicon.png"
apple_touch_icon: "/img/apple-touch-icon.png"
apple_touch_startup_image: "/img/vcm-banner-white.png"
language: "de"
language_direction: "ltr"
timezone: "Europe/Berlin"
city: "Müllheim"
postal: "79379"

color_primary: "#01A29A" # rgb(1,162,154) | Persian Green
color_secondary: "#366273" # rgb(54,98,115) | Blumine
color_dark: "#363B40" # rgb(54,59,64) | Baltic Sea
color_light: "#EFF5F5" # rgb(239,245,245) | Aqua Haze
color_success: "#BFA084" # rgb(191,160,132) | Rodeo Dust
color_info: "#666666" # rgb(102,102,102) | Dim Gray
color_danger: "#A3120A" # rgb(163,18,19) | Dark Red
color_warning: "#F09E1A" # rgb(240,158,26) | Vivid Orange

include:
  - _pages
  - _matches
  - _teams
permalink: /:title
url: https://vcmuellheim.de
author: "VC Müllheim"


# Jekyll GitHub Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 14
paginate_path: "/blog/:num/"

sass:
    sass_dir: _scss
    style: compressed

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: true

# Exclude these files from your production _site
exclude:
  - .github*
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .bundle*
  - /vendor/
  - node_modules

collections:
  club_members: # Adds Club Members to show on a contacts page
    sort_by: sortorder
  teams: # List teams on the landing page and additonaly include in rankings if they have an SBVV-ID
    output: true
    sort_by: liga
    permalink: /:collection/:name
  matches: # Creates pages for each SAMS matchSeries based on their filenames
    output: true
    permalink: /:collection/:name
  spielergebnisse: # individual matches
    sort_by: date
  rankings:
    sort_by: league_id
  announcements:
    sort_by: date

feed:
  collections:
    spielergebnisse:
      path: "/liga.xml"

prose:
  siteurl: 'https://vcmuellheim.de'
  media: 'upload'
  ignore:
    - /data
    - /_includes
    - /_layouts
    - /_matches
    - /_pages
    - /_sams
    - /_scss
    - /_spielergebnisse
    - /_teams
    - /.github
    - /assets
    - /blog
    - /docs
    - /edit
    - /img
    - /logo
    - _config.yml
    - .gitignore
    - 404.md
    - CNAME
    - Gemfile
    - index.md
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "thumbnail"
        field:
          element: "select"
          label: "Vorschaubild"
