---
title: Volleyball Club Müllheim
timezone: Europe/Berlin
collections:
  announcements:
    title: Announcements
    output: false
    sort_by: date
  club_members:
    title: Club Members
    output: false
    sort_by: sortorder
  posts:
    title: Posts
    output: true
  spielergebnisse:
    title: Spielergebnisse
    output: false
    sort_by: date
  sponsors:
    title: Sponsors
    output: false
  teams:
    title: Teams
    output: true
    permalink: "/:collection/:name"
    sort_by: liga
  uploads:
    title: Uploads
    output: true
name: VC Müllheim
short_name: VCM
official_name: Volleyballclub Müllheim e.V.
description: In Müllheim geh es in Sachen Volleyball richtig ab! Von Freizeit Team
  bis zur Verbandsliga. Hier findest du alle Infos und Neuigkeiten des Vereins.
logo: "/img/logo.png"
favicon: "/img/favicon.png"
apple_touch_icon: "/img/apple-touch-icon.png"
apple_touch_startup_image: "/img/vcm-banner-white.png"
language: de
language_direction: ltr
city: Müllheim
postal: '79379'
color_primary: "#01A29A"
color_secondary: "#366273"
color_dark: "#363B40"
color_light: "#EFF5F5"
color_success: "#BFA084"
color_info: "#666666"
color_danger: "#A3120A"
color_warning: "#F09E1A"
include:
- _pages
permalink: "/:title"
url: https://vcmuellheim.de
author: VC Müllheim
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-coffeescript
- jekyll-sass-converter
- jekyll-paginate
paginate: 14
paginate_path: "/blog/:num/"
sass:
  style: compressed
  load_paths:
  - _scss
  - node_modules
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
exclude:
- ".github*"
- ".gitignore"
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- ".sass-cache"
- ".vscode"
- ".bundle*"
- "/vendor/"
- node_modules
feed:
  collections:
    spielergebnisse:
      path: "/liga.xml"
