name: "VC M端llheim e.V."
short_name: "VCM"
title: "Volleyball Club M端llheim"
description: "In M端llheim geh es in Sachen Volleyball richtig ab! Von Freizeit Team bis zur Verbandsliga. Hier findest du alle Infos und Neuigkeiten des Vereins."
logo: "/img/logo.png"
favicon: "/img/favicon.png"
apple_touch_icon: "/img/apple-touch-icon.png"
apple_touch_startup_image: "/img/vcm-banner-white.png"
language: "de"
language_direction: "ltr"
theme_color: "#363b40"
background_color: "#366273"
include:
  - _pages
  - _matches
  - _teams
permalink: /:title
url: https://vcmuellheim.de
author: "VC M端llheim"


# Jekyll GitHub Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate

paginate: 8
paginate_path: "/blog/:num/"

sass:
    sass_dir: _scss
    style: compressed

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: true

# Exclude these files from your production _site
exclude:
  - .github*
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .bundle*
  - vendor*

collections:
  club_members: # Adds Club Members to show on a contacts page
    sort_by: sortorder
  teams: # List teams on the landing page and additonaly include in rankings if they have an SBVV-ID
    output: true
    sort_by: liga
    permalink: /:collection/:name
  teaminfo:
    sort_by: priority
  matches: # Creates pages for each SAMS matchSeries based on their filenames
    output: true
    permalink: /:collection/:name
  spielergebnisse: # individual matches
    sort_by: date
  heimspiele:
    sort_by: date
  rankings:
    sort_by: league_id

feed:
  collections:
    spielergebnisse:
      path: "/liga.xml"
