[console]
depth = 3

[test]
randomize = true
onlyFailures = true
preload = ["./test-setup.ts"]

[install]
linker = "hoisted"
auto = "disable"
# Only install package versions published at least 2 days ago
minimumReleaseAge = 172800
