name: "vc_muellheim_website"
services:
  nextjs:
    container_name: "nextjs-frontend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - sams_cache:/app/.temp/sams
    restart: always
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - /node_modules/
            - /app/data
        - action: sync
          path: ./data
          target: /app/data
        - action: rebuild
          path: package.json

volumes:
  sams_cache:
