
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **VARLOCK_ENV** 🔐 _sensitive_  
   * Auto-detected deployment environment (development, preview, staging, production, test)  
   */
  VARLOCK_ENV: string;
  
  /**
   * **CDK_ENVIRONMENT**  
   * -- AWS CDK configuration --  
   */
  CDK_ENVIRONMENT: "dev" | "prod";
  
  /** **CDK_BUDGET_ALERT_EMAIL** 🔐 _sensitive_ */
  CDK_BUDGET_ALERT_EMAIL?: string;
  
  /** **CDK_MONITORING_ALERT_EMAIL** 🔐 _sensitive_ */
  CDK_MONITORING_ALERT_EMAIL?: string;
  
  /**
   * **BETTER_AUTH_SECRET** 🔐 _sensitive_  
   * -- Better Auth configuration --  
   */
  BETTER_AUTH_SECRET: string;
  
  /**
   * **SAMS_API_KEY** 🔐 _sensitive_  
   * -- SAMS API credentials --  
   */
  SAMS_API_KEY: string;
  
  /**
   * **BEHOLD_FEED_URL** 🔐 _sensitive_  
   * -- Behold Instagram feed --  
   */
  BEHOLD_FEED_URL: string;
  
  /**
   * **MASTODON_ACCESS_TOKEN** 🔐 _sensitive_  
   * -- Mastodon API credentials --  
   *   
   * 📚 {@link https://freiburg.social/settings/applications | Mastodon access token for API authentication}  
   */
  MASTODON_ACCESS_TOKEN: string;
  
  /** **MASTODON_CLIENT_KEY** 🔐 _sensitive_ */
  MASTODON_CLIENT_KEY: string;
  
  /** **MASTODON_CLIENT_SECRET** 🔐 _sensitive_ */
  MASTODON_CLIENT_SECRET: string;
  
  /** **SENTRY_AUTH_TOKEN** 🔐 _sensitive_ */
  SENTRY_AUTH_TOKEN: string;
  
  /** **SENTRY_ENVIRONMENT** */
  SENTRY_ENVIRONMENT: "dev" | "prod";
  
};


declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, 'CDK_ENVIRONMENT' | 'SENTRY_ENVIRONMENT'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends EnvSchemaAsStrings {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }
}