---
new_page_extension: md
auto_deploy: false
admin_path: "/edit"
webhook_url: 
sections:
- type: directory
  path: _announcements
  label: Ankündigungen
  create: documents
  match: "**/*"
  templates:
  - ankundigung
- type: jekyll-posts
  label: News Beiträge
  create: documents
  templates:
  - neuen-beitrag-erstellen
- type: directory
  path: _teams
  label: Mannschaften
  create: documents
  match: "**/*"
  templates:
  - mannschaft-eintragen
- type: directory
  path: _club_members
  label: Vorstand & Vereinsämter
  create: documents
  match: "**/*"
  templates:
  - neues-vereinsmitglied-hinzufugen
upload_dir: upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
