/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardSponsorsRouteImport } from './routes/dashboard/sponsors'
import { Route as DashboardNewsRouteImport } from './routes/dashboard/news'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardLocationsRouteImport } from './routes/dashboard/locations'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardBusRouteImport } from './routes/dashboard/bus'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSponsorsRoute = DashboardSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocationsRoute = DashboardLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusRoute = DashboardBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/bus': typeof DashboardBusRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/bus': typeof DashboardBusRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/bus': typeof DashboardBusRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/locations': typeof DashboardLocationsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/sponsors': typeof DashboardSponsorsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/bus'
    | '/dashboard/events'
    | '/dashboard/locations'
    | '/dashboard/media'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/sponsors'
    | '/dashboard/teams'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/bus'
    | '/dashboard/events'
    | '/dashboard/locations'
    | '/dashboard/media'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/sponsors'
    | '/dashboard/teams'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/bus'
    | '/dashboard/events'
    | '/dashboard/locations'
    | '/dashboard/media'
    | '/dashboard/members'
    | '/dashboard/news'
    | '/dashboard/sponsors'
    | '/dashboard/teams'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsors': {
      id: '/dashboard/sponsors'
      path: '/sponsors'
      fullPath: '/dashboard/sponsors'
      preLoaderRoute: typeof DashboardSponsorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/locations': {
      id: '/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof DashboardLocationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bus': {
      id: '/dashboard/bus'
      path: '/bus'
      fullPath: '/dashboard/bus'
      preLoaderRoute: typeof DashboardBusRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBusRoute: typeof DashboardBusRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardLocationsRoute: typeof DashboardLocationsRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardSponsorsRoute: typeof DashboardSponsorsRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusRoute: DashboardBusRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardLocationsRoute: DashboardLocationsRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardSponsorsRoute: DashboardSponsorsRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
