backend:
  name: github
  repo: terijaki/vcmuellheim
  branch: main
  base_url: "https://api.netlify.com"
  auth_endpoint: auth
publish_mode: editorial_workflow
media_folder: "upload"
locale: "de"
site_url: "https://vcmuellheim.de"
display_url: "https://vcmuellheim.de"
logo_url: "https://vcmuellheim.de/logo/logo-schwarz.png"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Vorschaubild", name: "thumbnail", widget: "image", allow_multiple: false }
      - {label: "Fotogallerie", name: "gallery", widget: "image", allow_multiple: true }
      - {label: "Body", name: "body", widget: "markdown", buttons: [bold, italic, link, heading-one, quote, bulleted-list, numbered-list] }