import dayjs from "dayjs";
import { volunteerEventSchema, volunteerSignupSchema } from "@/lib/db/schemas";
import { putItems, type SeedContext } from "./common";

export async function seedVolunteerEventsData(ctx: SeedContext): Promise<void> {
  console.log("\n🤝 Seeding volunteer events...");

  const volunteerEvents = [
    {
      id: crypto.randomUUID(),
      type: "volunteerEvent" as const,
      title: "Frühjahrsputz im Vereinsheim",
      description: "Gemeinsames Aufräumen und Aufbereiten des Vereinsheims für die neue Saison.",
      location: "Vereinsheim VC Müllheim",
      organizerName: "Miriam Weber",
      organizerEmail: "volunteer@vc-muellheim.de",
      shifts: [
        {
          id: crypto.randomUUID(),
          label: "Aufräumen und Staub wischen",
          startDate: dayjs().subtract(32, "days").hour(9).minute(0).second(0).toISOString(),
          endDate: dayjs().subtract(32, "days").hour(12).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Helfer:in im Eingangsbereich",
              description: "Gäste begrüßen und die Räume vorbereiten.",
              minCapacity: 1,
              maxCapacity: 2,
            },
            {
              id: crypto.randomUUID(),
              label: "Küchenhilfe",
              description: "Küchenfläche vorbereiten und Abfall entsorgen.",
              minCapacity: 1,
              maxCapacity: 2,
            },
          ],
        },
        {
          id: crypto.randomUUID(),
          label: "Aufräumen und Staub wischen",
          startDate: dayjs().subtract(31, "day").hour(10).minute(0).second(0).toISOString(),
          endDate: dayjs().subtract(31, "day").hour(13).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Helfer:in im Eingangsbereich",
              description: "Gäste begrüßen und die Räume vorbereiten.",
              minCapacity: 1,
              maxCapacity: 2,
            },
            {
              id: crypto.randomUUID(),
              label: "Küchenhilfe",
              description: "Küchenfläche vorbereiten und Abfall entsorgen.",
              minCapacity: 1,
              maxCapacity: 2,
            },
          ],
        },
        {
          id: crypto.randomUUID(),
          label: "Fenster und Spiegel polieren",
          startDate: dayjs().subtract(31, "day").hour(13).minute(0).second(0).toISOString(),
          endDate: dayjs().subtract(31, "day").hour(16).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Fensterputz-Team",
              description: "Fenster und Spiegel reinigen.",
              minCapacity: 1,
              maxCapacity: 2,
            },
            {
              id: crypto.randomUUID(),
              label: "Küchenhilfe",
              description: "Küchenfläche vorbereiten und Abfall entsorgen.",
              minCapacity: 1,
              maxCapacity: 2,
            },
          ],
        },
      ],
      createdAt: dayjs().subtract(90, "days").toISOString(),
      updatedAt: dayjs().subtract(90, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerEvent" as const,
      title: "Kartenverkauf beim Sommerturnier",
      description: "Hilf beim Verkauf der Eintrittskarten und an der Information am Turniertag.",
      location: "Römerhalle Müllheim",
      organizerName: "Lars Zimmermann",
      organizerEmail: "turnierhilfe@vc-muellheim.de",
      shifts: [
        {
          id: crypto.randomUUID(),
          label: "Kartenverkauf am Eingang",
          startDate: dayjs().add(10, "days").hour(8).minute(30).second(0).toISOString(),
          endDate: dayjs().add(10, "days").hour(12).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Kassenhilfe",
              description: "Eintrittskarten verkaufen und Besucher informieren.",
              minCapacity: 1,
              maxCapacity: 2,
            },
          ],
        },
      ],
      createdAt: dayjs().subtract(5, "days").toISOString(),
      updatedAt: dayjs().subtract(5, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerEvent" as const,
      title: "Tag der offenen Tür für neue Mitglieder",
      description:
        "Wir begrüßen Interessierte und benötigen Unterstützung bei der Organisation und Betreuung.",
      location: "Vereinsheim VC Müllheim",
      organizerName: "Anna Hoffmann",
      organizerEmail: "oeffnung@vc-muellheim.de",
      shifts: [
        {
          id: crypto.randomUUID(),
          label: "Check-in und Begrüßung",
          startDate: dayjs().add(3, "weeks").hour(14).minute(0).second(0).toISOString(),
          endDate: dayjs().add(3, "weeks").hour(16).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Willkommens-Team",
              description: "Neue Gäste empfangen und durch den Abend führen.",
              minCapacity: 2,
              maxCapacity: 3,
            },
          ],
        },
        {
          id: crypto.randomUUID(),
          label: "Küche und Getränke",
          startDate: dayjs().add(3, "weeks").hour(15).minute(0).second(0).toISOString(),
          endDate: dayjs().add(3, "weeks").hour(18).minute(0).second(0).toISOString(),
          roles: [
            {
              id: crypto.randomUUID(),
              label: "Kiosk-Hilfe",
              description: "Getränke und kleine Snacks servieren.",
              minCapacity: 1,
              maxCapacity: 2,
            },
            {
              id: crypto.randomUUID(),
              label: "Küchenhilfe",
              description: "Unterstützung bei der Vorbereitung und dem Abbau.",
              minCapacity: 1,
              maxCapacity: 2,
            },
          ],
        },
      ],
      createdAt: dayjs().subtract(3, "days").toISOString(),
      updatedAt: dayjs().subtract(3, "days").toISOString(),
    },
  ];

  const validatedVolunteerEvents = volunteerEvents.map((event) =>
    volunteerEventSchema.parse(event),
  );

  await putItems(ctx.entities.volunteerEvent, validatedVolunteerEvents);

  const openHouseEventDate = dayjs().add(3, "weeks");
  const openHouseDateOfBirth = (yearsAgo: number) =>
    openHouseEventDate.subtract(yearsAgo, "years").format("YYYY-MM-DD");

  const volunteerSignups = [
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[0].id,
      shiftId: validatedVolunteerEvents[0].shifts[0].id,
      preferredRoleIds: [validatedVolunteerEvents[0].shifts[0].roles[0].id],
      assignedRoleId: validatedVolunteerEvents[0].shifts[0].roles[0].id,
      firstName: "Leonie",
      lastName: "Keller",
      email: "leonie.keller@example.com",
      dateOfBirth: openHouseDateOfBirth(28),
      association: "VC Müllheim",
      mobilePhone: "+4917612345678",
      note: "Kann auch am Nachmittag aushelfen.",
      createdAt: dayjs().subtract(8, "days").toISOString(),
      updatedAt: dayjs().subtract(8, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[0].id,
      shiftId: validatedVolunteerEvents[0].shifts[0].id,
      preferredRoleIds: [validatedVolunteerEvents[0].shifts[0].roles[1].id],
      assignedRoleId: validatedVolunteerEvents[0].shifts[0].roles[1].id,
      firstName: "Mira",
      lastName: "Hoffmann",
      email: "mira.hoffmann@example.com",
      dateOfBirth: openHouseDateOfBirth(26),
      association: "VC Müllheim",
      mobilePhone: "+4917798765432",
      note: "Könnte auch am zweiten Tag mitkommen.",
      createdAt: dayjs().subtract(7, "days").toISOString(),
      updatedAt: dayjs().subtract(7, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "pending" as const,
      eventId: validatedVolunteerEvents[0].id,
      shiftId: validatedVolunteerEvents[0].shifts[1].id,
      preferredRoleIds: [validatedVolunteerEvents[0].shifts[1].roles[0].id],
      firstName: "Timo",
      lastName: "Roth",
      email: "timo.roth@example.com",
      dateOfBirth: openHouseDateOfBirth(15),
      association: "VC Müllheim",
      mobilePhone: "+4915111223344",
      note: "Freut sich auf den zweiten Putztag.",
      createdAt: dayjs().subtract(6, "days").toISOString(),
      updatedAt: dayjs().subtract(6, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[0].id,
      shiftId: validatedVolunteerEvents[0].shifts[2].id,
      preferredRoleIds: [validatedVolunteerEvents[0].shifts[2].roles[1].id],
      assignedRoleId: validatedVolunteerEvents[0].shifts[2].roles[1].id,
      firstName: "Sara",
      lastName: "Klein",
      email: "sara.klein@example.com",
      dateOfBirth: openHouseDateOfBirth(33),
      association: "Müllheimer Volleyballfreunde",
      mobilePhone: "016044556677",
      note: "Kann auch im Fensterbereich aushelfen.",
      createdAt: dayjs().subtract(5, "days").toISOString(),
      updatedAt: dayjs().subtract(5, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "pending" as const,
      eventId: validatedVolunteerEvents[1].id,
      shiftId: validatedVolunteerEvents[1].shifts[0].id,
      preferredRoleIds: [validatedVolunteerEvents[1].shifts[0].roles[0].id],
      firstName: "Tim",
      lastName: "Schneider",
      email: "tim.schneider@example.com",
      dateOfBirth: openHouseDateOfBirth(34),
      association: "VC Müllheim",
      mobilePhone: "+4915123456789",
      note: "Ich freue mich auf den Turniertag.",
      createdAt: dayjs().subtract(2, "days").toISOString(),
      updatedAt: dayjs().subtract(2, "days").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[2].id,
      shiftId: validatedVolunteerEvents[2].shifts[0].id,
      preferredRoleIds: [validatedVolunteerEvents[2].shifts[0].roles[0].id],
      assignedRoleId: validatedVolunteerEvents[2].shifts[0].roles[0].id,
      firstName: "Nora",
      lastName: "Braun",
      email: "nora.braun@example.com",
      dateOfBirth: openHouseDateOfBirth(14),
      association: "Müllheimer Volleyballfreunde",
      createdAt: dayjs().subtract(1, "day").toISOString(),
      updatedAt: dayjs().subtract(1, "day").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[2].id,
      shiftId: validatedVolunteerEvents[2].shifts[1].id,
      preferredRoleIds: [validatedVolunteerEvents[2].shifts[1].roles[0].id],
      assignedRoleId: validatedVolunteerEvents[2].shifts[1].roles[0].id,
      firstName: "Mina",
      lastName: "Fischer",
      email: "mina.fischer@example.com",
      dateOfBirth: openHouseDateOfBirth(27),
      association: "VC Müllheim",
      mobilePhone: "016398765432",
      note: "Könnte auch beim Abbau unterstützen.",
      createdAt: dayjs().subtract(1, "day").toISOString(),
      updatedAt: dayjs().subtract(1, "day").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "pending" as const,
      eventId: validatedVolunteerEvents[2].id,
      shiftId: validatedVolunteerEvents[2].shifts[1].id,
      preferredRoleIds: [validatedVolunteerEvents[2].shifts[1].roles[1].id],
      firstName: "Jonas",
      lastName: "Wolf",
      email: "jonas.wolf@example.com",
      dateOfBirth: openHouseDateOfBirth(32),
      association: "VC Müllheim",
      mobilePhone: "+4915255667788",
      note: "Möchte gern in der Küche helfen.",
      createdAt: dayjs().subtract(1, "day").toISOString(),
      updatedAt: dayjs().subtract(1, "day").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "confirmed" as const,
      eventId: validatedVolunteerEvents[2].id,
      shiftId: validatedVolunteerEvents[2].shifts[1].id,
      preferredRoleIds: [validatedVolunteerEvents[2].shifts[1].roles[0].id],
      assignedRoleId: validatedVolunteerEvents[2].shifts[1].roles[0].id,
      firstName: "Lina",
      lastName: "Becker",
      email: "lina.becker@example.com",
      dateOfBirth: openHouseDateOfBirth(17),
      association: "Müllheimer Volleyballfreunde",
      mobilePhone: "+4917632109876",
      note: "Kann Getränke und Snacks übernehmen.",
      createdAt: dayjs().subtract(1, "day").toISOString(),
      updatedAt: dayjs().subtract(1, "day").toISOString(),
    },
    {
      id: crypto.randomUUID(),
      type: "volunteerSignup" as const,
      status: "pending" as const,
      eventId: validatedVolunteerEvents[2].id,
      shiftId: validatedVolunteerEvents[2].shifts[1].id,
      preferredRoleIds: [validatedVolunteerEvents[2].shifts[1].roles[1].id],
      firstName: "Emil",
      lastName: "Weiß",
      email: "emil.weiss@example.com",
      dateOfBirth: openHouseDateOfBirth(35),
      association: "VC Müllheim",
      mobilePhone: "+491721234890",
      note: "Hilft gern in der Küche und beim Aufräumen.",
      createdAt: dayjs().subtract(1, "day").toISOString(),
      updatedAt: dayjs().subtract(1, "day").toISOString(),
    },
  ];

  const validatedVolunteerSignups = volunteerSignups.map((signup) =>
    volunteerSignupSchema.parse(signup),
  );

  await putItems(ctx.entities.volunteerSignup, validatedVolunteerSignups);
  console.log(
    `✅ Seeded ${validatedVolunteerEvents.length} volunteer events and ${validatedVolunteerSignups.length} signups`,
  );
}
