// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zConstraintViolation = z.object({
    constraint: z.optional(z.string()),
    property: z.optional(z.string()),
    entity: z.optional(z.string()),
    invalidValue: z.optional(z.string()),
    message: z.optional(z.string())
});

export const zValidationError = z.object({
    violations: z.optional(z.array(zConstraintViolation))
});

export const zResponseExceptionMessage = z.object({
    message: z.optional(z.string())
});

export const zResponseException = z.object({
    exception: z.optional(z.string()),
    message: z.optional(z.string())
});

export const zEmbedded = z.object({
    empty: z.optional(z.boolean())
});

export const zLinks = z.object({
    empty: z.optional(z.boolean())
});

export const zHalRepresentation = z.object({
    _links: z.optional(zLinks),
    _embedded: z.optional(zEmbedded)
});

/**
 * Address for a location or a person. An address object may be null if no address data is available. For persons this might be the case if the address visibility has been set to private.
 */
export const zAddress = z.object({
    street: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    country: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    extrafield: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    region: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postbox: z.optional(z.union([
        z.string(),
        z.null()
    ]))
}).register(z.globalRegistry, {
    description: 'Address for a location or a person. An address object may be null if no address data is available. For persons this might be the case if the address visibility has been set to private.'
});

/**
 * A member of a committee. Personal data may be null if its visibility has been restricted.
 */
export const zCommitteeMember = z.object({
    uuid: z.optional(z.string()),
    committeeUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the committee'
    })),
    additionalTitle: z.optional(z.string()),
    sourceFunction: z.optional(z.string()),
    description: z.optional(z.string()),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    email: z.optional(z.string()),
    priority: z.optional(z.int()),
    address: z.optional(zAddress),
    phoneMobile: z.optional(z.string()),
    fax: z.optional(z.string()),
    phoneWork: z.optional(z.string()),
    faxWork: z.optional(z.string()),
    phoneMobileWork: z.optional(z.string()),
    portraitPhotoLink: z.optional(z.string())
}).register(z.globalRegistry, {
    description: 'A member of a committee. Personal data may be null if its visibility has been restricted.'
});

export const zMatchResultTypeCount = z.object({
    result: z.optional(z.string()),
    count: z.optional(z.int())
});

export const zRefereeTeamDto = z.object({
    firstReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    secondReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    thirdReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    challengeReferee: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zVolleyballMatchSetRestDto = z.object({
    number: z.optional(z.int()),
    ballPoints: z.optional(z.string()),
    winner: z.optional(z.string()),
    winnerName: z.optional(z.string()),
    duration: z.optional(z.int())
});

export const zVolleyballMatchResultsDto = z.object({
    winner: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    winnerName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    setPoints: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ballPoints: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sets: z.optional(z.union([
        z.array(zVolleyballMatchSetRestDto),
        z.null()
    ]))
});

export const zLinkDto = z.object({
    href: z.optional(z.string())
});

export const zAssociation = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    name: z.string(),
    shortname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parentUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    level: z.optional(z.union([
        z.int(),
        z.null()
    ]))
});

export const zAssociationResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zAssociation)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zCommittee = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    associationUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the association this entity belongs to'
    })),
    members: z.optional(z.array(zCommitteeMember)),
    name: z.optional(z.string()),
    shortname: z.optional(z.string()),
    description: z.optional(z.string()),
    type: z.optional(z.string()),
    imageLink: z.optional(z.string())
});

export const zCommitteePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zCommittee)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zSportsclubDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    name: z.string(),
    shortname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sportsclubNumber: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageLink: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zSportsclubPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zSportsclubDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueHierarchyDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    level: z.optional(z.int()),
    parentLeagueHierarchyUuid: z.optional(z.string())
});

export const zLeagueHierarchyPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLeagueHierarchyDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zCompetitionDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string()),
    superCompetitionUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'If this competition is the sub-competition of a super competition then this UUID points to this super competition.'
    }))
});

export const zCompetitionPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zCompetitionDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string())
});

export const zLeaguePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLeagueDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zSuperCompetitionDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string()),
    superCompetitionUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'If this competition is the sub-competition of a super competition then this UUID points to this super competition.'
    }))
});

export const zSuperCompetitionPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zSuperCompetitionDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

/**
 * A location comprises the location's name, its address, and its geographical coordinates if available
 */
export const zLocation = z.object({
    uuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    longitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    latitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    address: z.optional(zAddress)
}).register(z.globalRegistry, {
    description: 'A location comprises the location\'s name, its address, and its geographical coordinates if available'
});

export const zLocationResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLocation)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zCompetitionMatchGroupDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    tourneyLevel: z.optional(z.int()),
    seasonUuid: z.optional(z.string()),
    competitionUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string())
});

export const zCompetitionMatchGroupPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zCompetitionMatchGroupDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueRankingsEntryDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    teamName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    rank: z.optional(z.int()),
    matchesPlayed: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    points: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    scoreIncludingLosses: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    wins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    losses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setWins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setLosses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setDifference: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setRatio: z.optional(z.union([
        z.number(),
        z.string(),
        z.null()
    ])),
    ballWins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballLosses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballDifference: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballRatio: z.optional(z.union([
        z.number(),
        z.string(),
        z.null()
    ])),
    resultTypes: z.optional(z.union([
        z.array(zMatchResultTypeCount),
        z.null()
    ]))
});

export const zCompetitionMatchGroupRankingsDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    matchGroupName: z.optional(z.string()),
    rankings: z.optional(z.array(zLeagueRankingsEntryDto))
});

export const zCompetitionRankingsResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zCompetitionMatchGroupRankingsDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zTeamDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), z.unknown()),
        z.null()
    ])),
    masterTeamUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.string()),
    shortName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    teamNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    clubCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageLink: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageForScreenOutputLink: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sportsclubUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zTeamPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zTeamDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zCompetitionMatchDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.object({
            team1: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            })),
            team2: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            }))
        }),
        z.null()
    ])),
    date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    time: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    matchNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    decidingMatch: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    gameReassessed: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    host: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    referees: z.optional(zRefereeTeamDto),
    spectators: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    netDuration: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    verified: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    location: z.optional(zLocation),
    seasonUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team1Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team2Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    results: z.optional(zVolleyballMatchResultsDto),
    matchGroupUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    competitionUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    delayPossible: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    indefinitelyRescheduled: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

export const zCompetitionMatchPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zCompetitionMatchDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueMatchDayDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    matchdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    seasonUuid: z.optional(z.string()),
    leagueUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string())
});

export const zLeagueMatchDayPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLeagueMatchDayDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueRankingsResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLeagueRankingsEntryDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zLeagueMatchDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.object({
            team1: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            })),
            team2: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            }))
        }),
        z.null()
    ])),
    date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    time: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    matchNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    decidingMatch: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    gameReassessed: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    host: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    referees: z.optional(zRefereeTeamDto),
    spectators: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    netDuration: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    verified: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    location: z.optional(zLocation),
    seasonUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team1Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team2Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    results: z.optional(zVolleyballMatchResultsDto),
    matchDayUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    leagueUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    delayPossible: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    indefinitelyRescheduled: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

export const zLeagueMatchPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zLeagueMatchDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export const zEvent = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Event unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    shortname: z.optional(z.string()),
    eventNumber: z.optional(z.int()),
    overridingEventNumber: z.optional(z.string()),
    dateNotYetKnown: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'True if no start and end date has been set yet'
    })),
    endsAt: z.optional(z.iso.datetime({ offset: true, local: true })),
    beginsAt: z.optional(z.iso.datetime({ offset: true, local: true }).register(z.globalRegistry, {
        description: 'Start date for an event. Is null if dateNotYetKnown is true'
    })),
    registrationDeadline: z.optional(z.iso.datetime({ offset: true, local: true })),
    associationUuid: z.optional(z.string()),
    canceled: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'True if the event has been canceled'
    })),
    minimumNumberOfParticipants: z.optional(z.int()),
    maximumNumberOfParticipants: z.optional(z.int()),
    usedCapacity: z.optional(z.int().register(z.globalRegistry, {
        description: 'Number of registered participants for an event. If this event is a subordinate event, i.e. there is a higher level event, then this value is calculated as the sum of all participants of the higher level event and all participants of this higher level event\'s subordinate event. If this event has subordinate events, then this value is calculated as the sum of participants of this event and all its subordinate events.'
    })),
    registrationUri: z.optional(z.url()),
    location: z.optional(zLocation),
    eventTypeUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the type details for this event'
    }))
});

export const zEventPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    content: z.optional(z.array(zEvent)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

/**
 * Type of an event.
 */
export const zEventType = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    description: z.optional(z.string()),
    category: z.optional(z.string()),
    associationUuid: z.optional(z.string())
}).register(z.globalRegistry, {
    description: 'Type of an event.'
});

export const zSeasonDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    name: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    currentSeason: z.optional(z.boolean())
});

export const zUserDetailsDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), z.unknown())),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    dateOfBirth: z.optional(z.iso.datetime({ offset: true, local: true })),
    gender: z.optional(z.enum([
        'UNDEFINED',
        'MALE',
        'FEMALE',
        'DIVERS'
    ])),
    emailAddress: z.optional(z.string()),
    samsInstance: z.optional(z.string()),
    refsoftID: z.optional(z.string())
});

export const zGetApiBaseLinksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export const zGetAssociationByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested association'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAssociationByUuidResponse = zAssociation;

export const zGetAssociationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAssociationsResponse = zAssociationResourcePage;

export const zGetCommitteesForAssociationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the association whose committees are requested'
        })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCommitteesForAssociationResponse = zCommitteePage;

export const zGetSportsclubsForAssociationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the association whose committees are requested'
        })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetSportsclubsForAssociationResponse = zSportsclubPage;

export const zGetAllCommitteesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllCommitteesResponse = zCommitteePage;

export const zGetCommitteeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCommitteeResponse = zCommittee;

export const zGetAllLeagueHierarchiesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for the season. UUID of the season to which the league hierarchy belongs.'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllLeagueHierarchiesResponse = zLeagueHierarchyPage;

export const zGetCompetitionsByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCompetitionsByLeagueHierarchyResponse = zCompetitionPage;

export const zGetLeagueHierarchyByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLeagueHierarchyByUuidResponse = zLeagueHierarchyDto;

export const zGetLeaguesByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLeaguesByLeagueHierarchyResponse = zLeaguePage;

export const zGetSuperCompetitionsByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetSuperCompetitionsByLeagueHierarchyResponse = zSuperCompetitionPage;

export const zGetAllLocationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllLocationsResponse = zLocationResourcePage;

export const zGetLocationByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLocationByUuidResponse = zLocation;

export const zGetAllCompetitionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllCompetitionsResponse = zCompetitionPage;

export const zGetCompetitionByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCompetitionByUuidResponse = zCompetitionDto;

export const zGetMatchGroupsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchGroupsForCompetitionResponse = zCompetitionMatchGroupPage;

export const zGetRankingsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetRankingsForCompetitionResponse = zCompetitionRankingsResourcePage;

export const zGetTeamsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetTeamsForCompetitionResponse = zTeamPage;

export const zGetAllCompetitionMatchesWithFilterData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by season UUID: Find all matches from a particular season.'
        })),
        'for-competition': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by competition UUID: Find all matches from a particular competition.'
        })),
        'for-sportsclub': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by sports club UUID: Find all matches for a particular sports club.'
        })),
        'for-team': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by team UUID: Find all matches attended by a particular team.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllCompetitionMatchesWithFilterResponse = zCompetitionMatchPage;

export const zGetCompetitionMatchByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCompetitionMatchByUuidResponse = zCompetitionMatchDto;

export const zGetAllMatchGroupsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllMatchGroupsResponse = zCompetitionMatchGroupPage;

export const zGetMatchGroupByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchGroupByUuidResponse = zCompetitionMatchGroupDto;

export const zGetMatchesByMatchGroupData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchesByMatchGroupResponse = zCompetitionMatchPage;

export const zGetAllLeaguesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllLeaguesResponse = zLeaguePage;

export const zGetLeagueByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLeagueByUuidResponse = zLeagueDto;

export const zGetMatchDaysForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchDaysForLeagueResponse = zLeagueMatchDayPage;

export const zGetRankingsForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetRankingsForLeagueResponse = zLeagueRankingsResourcePage;

export const zGetTeamsForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetTeamsForLeagueResponse = zTeamPage;

export const zGetAllLeagueMatchesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by season UUID: Find all matches from a particular season.'
        })),
        'for-league': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by league UUID: Find all matches from a particular league.'
        })),
        'for-sportsclub': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by sports club UUID: Find all matches for a particular sports club.'
        })),
        'for-team': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by team UUID: Find all matches attended by a particular team.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllLeagueMatchesResponse = zLeagueMatchPage;

export const zGetLeagueMatchByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLeagueMatchByUuidResponse = zLeagueMatchDto;

export const zGetAllMatchDaysData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllMatchDaysResponse = zLeagueMatchDayPage;

export const zGetMatchDayByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchDayByUuidResponse = zLeagueMatchDayDto;

export const zGetMatchesByMatchDayData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetMatchesByMatchDayResponse = zLeagueMatchPage;

export const zGetAllSuperCompetitionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllSuperCompetitionsResponse = zSuperCompetitionPage;

export const zGetSuperCompetitionByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetSuperCompetitionByUuidResponse = zSuperCompetitionDto;

export const zGetAllEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllEventsResponse = zEventPage;

export const zGetEventByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested event'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetEventByUuidResponse = zEvent;

export const zGetEventTypeByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested event type'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetEventTypeByUuidResponse = zEventType;

export const zGetEventTypesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetEventTypesResponse = zEventType;

export const zGetAllSeasonsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllSeasonsResponse = z.array(zSeasonDto).register(z.globalRegistry, {
    description: 'Successful operation'
});

export const zGetLeagueHierarchiesForSeasonData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetLeagueHierarchiesForSeasonResponse = zLeagueHierarchyPage;

export const zGetSeasonByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetSeasonByUuidResponse = zSeasonDto;

export const zGetAllSportsclubsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllSportsclubsResponse = zSportsclubPage;

export const zGetSportsclubData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetSportsclubResponse = zSportsclubDto;

export const zGetAllTeamsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetAllTeamsResponse = zTeamPage;

export const zGetTeamByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetTeamByUuidResponse = zTeamDto;

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zGetCurrentUserResponse = zUserDetailsDto;

export const zUserDetailsRootLinksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

/**
 * Successful operation
 */
export const zUserDetailsRootLinksResponse = zHalRepresentation;
