// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zConstraintViolation = z.object({
    constraint: z.optional(z.string()),
    property: z.optional(z.string()),
    entity: z.optional(z.string()),
    invalidValue: z.optional(z.string()),
    message: z.optional(z.string())
});

export type ConstraintViolationZodType = z.infer<typeof zConstraintViolation>;

export const zValidationError = z.object({
    violations: z.optional(z.array(zConstraintViolation))
});

export type ValidationErrorZodType = z.infer<typeof zValidationError>;

export const zResponseExceptionMessage = z.object({
    message: z.optional(z.string())
});

export type ResponseExceptionMessageZodType = z.infer<typeof zResponseExceptionMessage>;

export const zResponseException = z.object({
    exception: z.optional(z.string()),
    message: z.optional(z.string())
});

export type ResponseExceptionZodType = z.infer<typeof zResponseException>;

export const zEmbedded = z.object({
    empty: z.optional(z.boolean())
});

export type EmbeddedZodType = z.infer<typeof zEmbedded>;

export const zLinks = z.object({
    empty: z.optional(z.boolean())
});

export type LinksZodType = z.infer<typeof zLinks>;

export const zHalRepresentation = z.object({
    _links: z.optional(zLinks),
    _embedded: z.optional(zEmbedded)
});

export type HalRepresentationZodType = z.infer<typeof zHalRepresentation>;

/**
 * Address for a location or a person. An address object may be null if no address data is available. For persons this might be the case if the address visibility has been set to private.
 */
export const zAddress = z.object({
    street: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    country: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    extrafield: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    region: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postbox: z.optional(z.union([
        z.string(),
        z.null()
    ]))
}).register(z.globalRegistry, {
    description: 'Address for a location or a person. An address object may be null if no address data is available. For persons this might be the case if the address visibility has been set to private.'
});

export type AddressZodType = z.infer<typeof zAddress>;

/**
 * A member of a committee. Personal data may be null if its visibility has been restricted.
 */
export const zCommitteeMember = z.object({
    uuid: z.optional(z.string()),
    committeeUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the committee'
    })),
    additionalTitle: z.optional(z.string()),
    sourceFunction: z.optional(z.string()),
    description: z.optional(z.string()),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    email: z.optional(z.string()),
    priority: z.optional(z.int()),
    address: z.optional(zAddress),
    phoneMobile: z.optional(z.string()),
    fax: z.optional(z.string()),
    phoneWork: z.optional(z.string()),
    faxWork: z.optional(z.string()),
    phoneMobileWork: z.optional(z.string()),
    portraitPhotoLink: z.optional(z.string())
}).register(z.globalRegistry, {
    description: 'A member of a committee. Personal data may be null if its visibility has been restricted.'
});

export type CommitteeMemberZodType = z.infer<typeof zCommitteeMember>;

export const zMatchResultTypeCount = z.object({
    result: z.optional(z.string()),
    count: z.optional(z.int())
});

export type MatchResultTypeCountZodType = z.infer<typeof zMatchResultTypeCount>;

export const zRefereeTeamDto = z.object({
    firstReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    secondReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    thirdReferee: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    challengeReferee: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type RefereeTeamDtoZodType = z.infer<typeof zRefereeTeamDto>;

export const zVolleyballMatchSetRestDto = z.object({
    number: z.optional(z.int()),
    ballPoints: z.optional(z.string()),
    winner: z.optional(z.string()),
    winnerName: z.optional(z.string()),
    duration: z.optional(z.int())
});

export type VolleyballMatchSetRestDtoZodType = z.infer<typeof zVolleyballMatchSetRestDto>;

export const zVolleyballMatchResultsDto = z.object({
    winner: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    winnerName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    setPoints: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    ballPoints: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sets: z.optional(z.union([
        z.array(zVolleyballMatchSetRestDto),
        z.null()
    ]))
});

export type VolleyballMatchResultsDtoZodType = z.infer<typeof zVolleyballMatchResultsDto>;

export const zLinkDto = z.object({
    href: z.optional(z.string())
});

export type LinkDtoZodType = z.infer<typeof zLinkDto>;

export const zObject = z.record(z.string(), z.unknown());

export type ObjectZodType = z.infer<typeof zObject>;

export const zAssociation = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), zObject),
        z.null()
    ])),
    name: z.string(),
    shortname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    parentUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    level: z.optional(z.union([
        z.int(),
        z.null()
    ]))
});

export type AssociationZodType = z.infer<typeof zAssociation>;

export const zAssociationResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zAssociation)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type AssociationResourcePageZodType = z.infer<typeof zAssociationResourcePage>;

export const zCommittee = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    associationUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the association this entity belongs to'
    })),
    members: z.optional(z.array(zCommitteeMember)),
    name: z.optional(z.string()),
    shortname: z.optional(z.string()),
    description: z.optional(z.string()),
    type: z.optional(z.string()),
    imageLink: z.optional(z.string())
});

export type CommitteeZodType = z.infer<typeof zCommittee>;

export const zCommitteePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zCommittee)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type CommitteePageZodType = z.infer<typeof zCommitteePage>;

export const zSportsclubDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), zObject),
        z.null()
    ])),
    name: z.string(),
    shortname: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sportsclubNumber: z.optional(z.union([
        z.coerce.bigint(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageLink: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type SportsclubDtoZodType = z.infer<typeof zSportsclubDto>;

export const zSportsclubPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zSportsclubDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type SportsclubPageZodType = z.infer<typeof zSportsclubPage>;

export const zLeagueHierarchyDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    level: z.optional(z.int()),
    parentLeagueHierarchyUuid: z.optional(z.string())
});

export type LeagueHierarchyDtoZodType = z.infer<typeof zLeagueHierarchyDto>;

export const zLeagueHierarchyPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLeagueHierarchyDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LeagueHierarchyPageZodType = z.infer<typeof zLeagueHierarchyPage>;

export const zCompetitionDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string()),
    superCompetitionUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'If this competition is the sub-competition of a super competition then this UUID points to this super competition.'
    }))
});

export type CompetitionDtoZodType = z.infer<typeof zCompetitionDto>;

export const zCompetitionPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zCompetitionDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type CompetitionPageZodType = z.infer<typeof zCompetitionPage>;

export const zLeagueDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string())
});

export type LeagueDtoZodType = z.infer<typeof zLeagueDto>;

export const zLeaguePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLeagueDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LeaguePageZodType = z.infer<typeof zLeaguePage>;

export const zSuperCompetitionDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    shortName: z.optional(z.string()),
    gender: z.optional(z.enum([
        'MALE',
        'FEMALE',
        'MIXED'
    ])),
    leagueHierarchyUuid: z.optional(z.string()),
    seasonUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string()),
    latestResultUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    latestStructuralUpdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    scoreTableCalculationMode: z.optional(z.string()),
    superCompetitionUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'If this competition is the sub-competition of a super competition then this UUID points to this super competition.'
    }))
});

export type SuperCompetitionDtoZodType = z.infer<typeof zSuperCompetitionDto>;

export const zSuperCompetitionPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zSuperCompetitionDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type SuperCompetitionPageZodType = z.infer<typeof zSuperCompetitionPage>;

/**
 * A location comprises the location's name, its address, and its geographical coordinates if available
 */
export const zLocation = z.object({
    uuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), zObject),
        z.null()
    ])),
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    longitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    latitude: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    address: z.optional(zAddress)
}).register(z.globalRegistry, {
    description: 'A location comprises the location\'s name, its address, and its geographical coordinates if available'
});

export type LocationZodType = z.infer<typeof zLocation>;

export const zLocationResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLocation)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LocationResourcePageZodType = z.infer<typeof zLocationResourcePage>;

export const zCompetitionMatchGroupDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    tourneyLevel: z.optional(z.int()),
    seasonUuid: z.optional(z.string()),
    competitionUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string())
});

export type CompetitionMatchGroupDtoZodType = z.infer<typeof zCompetitionMatchGroupDto>;

export const zCompetitionMatchGroupPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zCompetitionMatchGroupDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type CompetitionMatchGroupPageZodType = z.infer<typeof zCompetitionMatchGroupPage>;

export const zLeagueRankingsEntryDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), zObject),
        z.null()
    ])),
    teamName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    rank: z.optional(z.int()),
    matchesPlayed: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    points: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    scoreIncludingLosses: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    wins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    losses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setWins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setLosses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setDifference: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    setRatio: z.optional(z.union([
        z.number(),
        z.string(),
        z.null()
    ])),
    ballWins: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballLosses: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballDifference: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    ballRatio: z.optional(z.union([
        z.number(),
        z.string(),
        z.null()
    ])),
    resultTypes: z.optional(z.union([
        z.array(zMatchResultTypeCount),
        z.null()
    ]))
});

export type LeagueRankingsEntryDtoZodType = z.infer<typeof zLeagueRankingsEntryDto>;

export const zCompetitionMatchGroupRankingsDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    matchGroupName: z.optional(z.string()),
    rankings: z.optional(z.array(zLeagueRankingsEntryDto))
});

export type CompetitionMatchGroupRankingsDtoZodType = z.infer<typeof zCompetitionMatchGroupRankingsDto>;

export const zCompetitionRankingsResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zCompetitionMatchGroupRankingsDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type CompetitionRankingsResourcePageZodType = z.infer<typeof zCompetitionRankingsResourcePage>;

export const zTeamDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.record(z.string(), zObject),
        z.null()
    ])),
    masterTeamUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.string()),
    shortName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    teamNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    clubCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageLink: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    logoImageForScreenOutputLink: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    sportsclubUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export type TeamDtoZodType = z.infer<typeof zTeamDto>;

export const zTeamPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zTeamDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type TeamPageZodType = z.infer<typeof zTeamPage>;

export const zCompetitionMatchDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.object({
            team1: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            })),
            team2: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            }))
        }),
        z.null()
    ])),
    date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    time: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    matchNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    decidingMatch: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    gameReassessed: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    host: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    referees: z.optional(zRefereeTeamDto),
    spectators: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    netDuration: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    verified: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    location: z.optional(zLocation),
    seasonUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team1Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team2Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    results: z.optional(zVolleyballMatchResultsDto),
    matchGroupUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    competitionUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    delayPossible: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    indefinitelyRescheduled: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

export type CompetitionMatchDtoZodType = z.infer<typeof zCompetitionMatchDto>;

export const zCompetitionMatchPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zCompetitionMatchDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type CompetitionMatchPageZodType = z.infer<typeof zCompetitionMatchPage>;

export const zLeagueMatchDayDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    matchdate: z.optional(z.iso.datetime({ offset: true, local: true })),
    seasonUuid: z.optional(z.string()),
    leagueUuid: z.optional(z.string()),
    associationUuid: z.optional(z.string())
});

export type LeagueMatchDayDtoZodType = z.infer<typeof zLeagueMatchDayDto>;

export const zLeagueMatchDayPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLeagueMatchDayDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LeagueMatchDayPageZodType = z.infer<typeof zLeagueMatchDayPage>;

export const zLeagueRankingsResourcePage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLeagueRankingsEntryDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LeagueRankingsResourcePageZodType = z.infer<typeof zLeagueRankingsResourcePage>;

export const zLeagueMatchDto = z.object({
    uuid: z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    }),
    _links: z.optional(z.union([
        z.record(z.string(), zLinkDto),
        z.null()
    ])),
    _embedded: z.optional(z.union([
        z.object({
            team1: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            })),
            team2: z.optional(z.object({
                uuid: z.string(),
                name: z.string(),
                sportsclubUuid: z.string()
            }))
        }),
        z.null()
    ])),
    date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    time: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    matchNumber: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    decidingMatch: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    gameReassessed: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    host: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    referees: z.optional(zRefereeTeamDto),
    spectators: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    netDuration: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    verified: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    location: z.optional(zLocation),
    seasonUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    associationUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team1Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    team2Description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    results: z.optional(zVolleyballMatchResultsDto),
    matchDayUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    leagueUuid: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    delayPossible: z.optional(z.union([
        z.boolean(),
        z.null()
    ])),
    indefinitelyRescheduled: z.optional(z.union([
        z.boolean(),
        z.null()
    ]))
});

export type LeagueMatchDtoZodType = z.infer<typeof zLeagueMatchDto>;

export const zLeagueMatchPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zLeagueMatchDto)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type LeagueMatchPageZodType = z.infer<typeof zLeagueMatchPage>;

export const zEvent = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Event unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    shortname: z.optional(z.string()),
    eventNumber: z.optional(z.int()),
    overridingEventNumber: z.optional(z.string()),
    dateNotYetKnown: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'True if no start and end date has been set yet'
    })),
    endsAt: z.optional(z.iso.datetime({ offset: true, local: true })),
    beginsAt: z.optional(z.iso.datetime({ offset: true, local: true }).register(z.globalRegistry, {
        description: 'Start date for an event. Is null if dateNotYetKnown is true'
    })),
    registrationDeadline: z.optional(z.iso.datetime({ offset: true, local: true })),
    associationUuid: z.optional(z.string()),
    canceled: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'True if the event has been canceled'
    })),
    minimumNumberOfParticipants: z.optional(z.int()),
    maximumNumberOfParticipants: z.optional(z.int()),
    usedCapacity: z.optional(z.int().register(z.globalRegistry, {
        description: 'Number of registered participants for an event. If this event is a subordinate event, i.e. there is a higher level event, then this value is calculated as the sum of all participants of the higher level event and all participants of this higher level event\'s subordinate event. If this event has subordinate events, then this value is calculated as the sum of participants of this event and all its subordinate events.'
    })),
    registrationUri: z.optional(z.url()),
    location: z.optional(zLocation),
    eventTypeUuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Reference to the type details for this event'
    }))
});

export type EventZodType = z.infer<typeof zEvent>;

export const zEventPage = z.object({
    totalElements: z.optional(z.int()),
    numberOfElements: z.optional(z.int()),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    content: z.optional(z.array(zEvent)),
    empty: z.optional(z.boolean()),
    totalPages: z.optional(z.int()),
    first: z.optional(z.boolean()),
    last: z.optional(z.boolean())
});

export type EventPageZodType = z.infer<typeof zEventPage>;

/**
 * Type of an event.
 */
export const zEventType = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    description: z.optional(z.string()),
    category: z.optional(z.string()),
    associationUuid: z.optional(z.string())
}).register(z.globalRegistry, {
    description: 'Type of an event.'
});

export type EventTypeZodType = z.infer<typeof zEventType>;

export const zSeasonDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    name: z.optional(z.string()),
    startDate: z.optional(z.string()),
    endDate: z.optional(z.string()),
    currentSeason: z.optional(z.boolean())
});

export type SeasonDtoZodType = z.infer<typeof zSeasonDto>;

export const zUserDetailsDto = z.object({
    uuid: z.optional(z.string().register(z.globalRegistry, {
        description: 'Entity unique identifier'
    })),
    _links: z.optional(z.record(z.string(), zLinkDto)),
    _embedded: z.optional(z.record(z.string(), zObject)),
    firstName: z.optional(z.string()),
    lastName: z.optional(z.string()),
    dateOfBirth: z.optional(z.iso.datetime({ offset: true, local: true })),
    gender: z.optional(z.enum([
        'UNDEFINED',
        'MALE',
        'FEMALE',
        'DIVERS'
    ])),
    emailAddress: z.optional(z.string()),
    samsInstance: z.optional(z.string()),
    refsoftID: z.optional(z.string())
});

export type UserDetailsDtoZodType = z.infer<typeof zUserDetailsDto>;

export const zGetApiBaseLinksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetApiBaseLinksDataZodType = z.infer<typeof zGetApiBaseLinksData>;

export const zGetAssociationByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested association'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAssociationByUuidDataZodType = z.infer<typeof zGetAssociationByUuidData>;

/**
 * Successful operation
 */
export const zGetAssociationByUuidResponse = zAssociation;

export type GetAssociationByUuidResponseZodType = z.infer<typeof zGetAssociationByUuidResponse>;

export const zGetAssociationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAssociationsDataZodType = z.infer<typeof zGetAssociationsData>;

/**
 * Successful operation
 */
export const zGetAssociationsResponse = zAssociationResourcePage;

export type GetAssociationsResponseZodType = z.infer<typeof zGetAssociationsResponse>;

export const zGetCommitteesForAssociationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the association whose committees are requested'
        })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCommitteesForAssociationDataZodType = z.infer<typeof zGetCommitteesForAssociationData>;

/**
 * Successful operation
 */
export const zGetCommitteesForAssociationResponse = zCommitteePage;

export type GetCommitteesForAssociationResponseZodType = z.infer<typeof zGetCommitteesForAssociationResponse>;

export const zGetSportsclubsForAssociationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the association whose committees are requested'
        })
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetSportsclubsForAssociationDataZodType = z.infer<typeof zGetSportsclubsForAssociationData>;

/**
 * Successful operation
 */
export const zGetSportsclubsForAssociationResponse = zSportsclubPage;

export type GetSportsclubsForAssociationResponseZodType = z.infer<typeof zGetSportsclubsForAssociationResponse>;

export const zGetAllCommitteesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllCommitteesDataZodType = z.infer<typeof zGetAllCommitteesData>;

/**
 * Successful operation
 */
export const zGetAllCommitteesResponse = zCommitteePage;

export type GetAllCommitteesResponseZodType = z.infer<typeof zGetAllCommitteesResponse>;

export const zGetCommitteeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCommitteeDataZodType = z.infer<typeof zGetCommitteeData>;

/**
 * Successful operation
 */
export const zGetCommitteeResponse = zCommittee;

export type GetCommitteeResponseZodType = z.infer<typeof zGetCommitteeResponse>;

export const zGetAllLeagueHierarchiesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for the season. UUID of the season to which the league hierarchy belongs.'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllLeagueHierarchiesDataZodType = z.infer<typeof zGetAllLeagueHierarchiesData>;

/**
 * Successful operation
 */
export const zGetAllLeagueHierarchiesResponse = zLeagueHierarchyPage;

export type GetAllLeagueHierarchiesResponseZodType = z.infer<typeof zGetAllLeagueHierarchiesResponse>;

export const zGetCompetitionsByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCompetitionsByLeagueHierarchyDataZodType = z.infer<typeof zGetCompetitionsByLeagueHierarchyData>;

/**
 * Successful operation
 */
export const zGetCompetitionsByLeagueHierarchyResponse = zCompetitionPage;

export type GetCompetitionsByLeagueHierarchyResponseZodType = z.infer<typeof zGetCompetitionsByLeagueHierarchyResponse>;

export const zGetLeagueHierarchyByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLeagueHierarchyByUuidDataZodType = z.infer<typeof zGetLeagueHierarchyByUuidData>;

/**
 * Successful operation
 */
export const zGetLeagueHierarchyByUuidResponse = zLeagueHierarchyDto;

export type GetLeagueHierarchyByUuidResponseZodType = z.infer<typeof zGetLeagueHierarchyByUuidResponse>;

export const zGetLeaguesByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLeaguesByLeagueHierarchyDataZodType = z.infer<typeof zGetLeaguesByLeagueHierarchyData>;

/**
 * Successful operation
 */
export const zGetLeaguesByLeagueHierarchyResponse = zLeaguePage;

export type GetLeaguesByLeagueHierarchyResponseZodType = z.infer<typeof zGetLeaguesByLeagueHierarchyResponse>;

export const zGetSuperCompetitionsByLeagueHierarchyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetSuperCompetitionsByLeagueHierarchyDataZodType = z.infer<typeof zGetSuperCompetitionsByLeagueHierarchyData>;

/**
 * Successful operation
 */
export const zGetSuperCompetitionsByLeagueHierarchyResponse = zSuperCompetitionPage;

export type GetSuperCompetitionsByLeagueHierarchyResponseZodType = z.infer<typeof zGetSuperCompetitionsByLeagueHierarchyResponse>;

export const zGetAllLocationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllLocationsDataZodType = z.infer<typeof zGetAllLocationsData>;

/**
 * Successful operation
 */
export const zGetAllLocationsResponse = zLocationResourcePage;

export type GetAllLocationsResponseZodType = z.infer<typeof zGetAllLocationsResponse>;

export const zGetLocationByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLocationByUuidDataZodType = z.infer<typeof zGetLocationByUuidData>;

/**
 * Successful operation
 */
export const zGetLocationByUuidResponse = zLocation;

export type GetLocationByUuidResponseZodType = z.infer<typeof zGetLocationByUuidResponse>;

export const zGetAllCompetitionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllCompetitionsDataZodType = z.infer<typeof zGetAllCompetitionsData>;

/**
 * Successful operation
 */
export const zGetAllCompetitionsResponse = zCompetitionPage;

export type GetAllCompetitionsResponseZodType = z.infer<typeof zGetAllCompetitionsResponse>;

export const zGetCompetitionByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCompetitionByUuidDataZodType = z.infer<typeof zGetCompetitionByUuidData>;

/**
 * Successful operation
 */
export const zGetCompetitionByUuidResponse = zCompetitionDto;

export type GetCompetitionByUuidResponseZodType = z.infer<typeof zGetCompetitionByUuidResponse>;

export const zGetMatchGroupsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchGroupsForCompetitionDataZodType = z.infer<typeof zGetMatchGroupsForCompetitionData>;

/**
 * Successful operation
 */
export const zGetMatchGroupsForCompetitionResponse = zCompetitionMatchGroupPage;

export type GetMatchGroupsForCompetitionResponseZodType = z.infer<typeof zGetMatchGroupsForCompetitionResponse>;

export const zGetRankingsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetRankingsForCompetitionDataZodType = z.infer<typeof zGetRankingsForCompetitionData>;

/**
 * Successful operation
 */
export const zGetRankingsForCompetitionResponse = zCompetitionRankingsResourcePage;

export type GetRankingsForCompetitionResponseZodType = z.infer<typeof zGetRankingsForCompetitionResponse>;

export const zGetTeamsForCompetitionData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetTeamsForCompetitionDataZodType = z.infer<typeof zGetTeamsForCompetitionData>;

/**
 * Successful operation
 */
export const zGetTeamsForCompetitionResponse = zTeamPage;

export type GetTeamsForCompetitionResponseZodType = z.infer<typeof zGetTeamsForCompetitionResponse>;

export const zGetAllCompetitionMatchesWithFilterData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by season UUID: Find all matches from a particular season.'
        })),
        'for-competition': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by competition UUID: Find all matches from a particular competition.'
        })),
        'for-sportsclub': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by sports club UUID: Find all matches for a particular sports club.'
        })),
        'for-team': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by team UUID: Find all matches attended by a particular team.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllCompetitionMatchesWithFilterDataZodType = z.infer<typeof zGetAllCompetitionMatchesWithFilterData>;

/**
 * Successful operation
 */
export const zGetAllCompetitionMatchesWithFilterResponse = zCompetitionMatchPage;

export type GetAllCompetitionMatchesWithFilterResponseZodType = z.infer<typeof zGetAllCompetitionMatchesWithFilterResponse>;

export const zGetCompetitionMatchByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCompetitionMatchByUuidDataZodType = z.infer<typeof zGetCompetitionMatchByUuidData>;

/**
 * Successful operation
 */
export const zGetCompetitionMatchByUuidResponse = zCompetitionMatchDto;

export type GetCompetitionMatchByUuidResponseZodType = z.infer<typeof zGetCompetitionMatchByUuidResponse>;

export const zGetAllMatchGroupsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllMatchGroupsDataZodType = z.infer<typeof zGetAllMatchGroupsData>;

/**
 * Successful operation
 */
export const zGetAllMatchGroupsResponse = zCompetitionMatchGroupPage;

export type GetAllMatchGroupsResponseZodType = z.infer<typeof zGetAllMatchGroupsResponse>;

export const zGetMatchGroupByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchGroupByUuidDataZodType = z.infer<typeof zGetMatchGroupByUuidData>;

/**
 * Successful operation
 */
export const zGetMatchGroupByUuidResponse = zCompetitionMatchGroupDto;

export type GetMatchGroupByUuidResponseZodType = z.infer<typeof zGetMatchGroupByUuidResponse>;

export const zGetMatchesByMatchGroupData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchesByMatchGroupDataZodType = z.infer<typeof zGetMatchesByMatchGroupData>;

/**
 * Successful operation
 */
export const zGetMatchesByMatchGroupResponse = zCompetitionMatchPage;

export type GetMatchesByMatchGroupResponseZodType = z.infer<typeof zGetMatchesByMatchGroupResponse>;

export const zGetAllLeaguesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllLeaguesDataZodType = z.infer<typeof zGetAllLeaguesData>;

/**
 * Successful operation
 */
export const zGetAllLeaguesResponse = zLeaguePage;

export type GetAllLeaguesResponseZodType = z.infer<typeof zGetAllLeaguesResponse>;

export const zGetLeagueByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLeagueByUuidDataZodType = z.infer<typeof zGetLeagueByUuidData>;

/**
 * Successful operation
 */
export const zGetLeagueByUuidResponse = zLeagueDto;

export type GetLeagueByUuidResponseZodType = z.infer<typeof zGetLeagueByUuidResponse>;

export const zGetMatchDaysForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchDaysForLeagueDataZodType = z.infer<typeof zGetMatchDaysForLeagueData>;

/**
 * Successful operation
 */
export const zGetMatchDaysForLeagueResponse = zLeagueMatchDayPage;

export type GetMatchDaysForLeagueResponseZodType = z.infer<typeof zGetMatchDaysForLeagueResponse>;

export const zGetRankingsForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetRankingsForLeagueDataZodType = z.infer<typeof zGetRankingsForLeagueData>;

/**
 * Successful operation
 */
export const zGetRankingsForLeagueResponse = zLeagueRankingsResourcePage;

export type GetRankingsForLeagueResponseZodType = z.infer<typeof zGetRankingsForLeagueResponse>;

export const zGetTeamsForLeagueData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetTeamsForLeagueDataZodType = z.infer<typeof zGetTeamsForLeagueData>;

/**
 * Successful operation
 */
export const zGetTeamsForLeagueResponse = zTeamPage;

export type GetTeamsForLeagueResponseZodType = z.infer<typeof zGetTeamsForLeagueResponse>;

export const zGetAllLeagueMatchesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        'for-season': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by season UUID: Find all matches from a particular season.'
        })),
        'for-league': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by league UUID: Find all matches from a particular league.'
        })),
        'for-sportsclub': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by sports club UUID: Find all matches for a particular sports club.'
        })),
        'for-team': z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter by team UUID: Find all matches attended by a particular team.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllLeagueMatchesDataZodType = z.infer<typeof zGetAllLeagueMatchesData>;

/**
 * Successful operation
 */
export const zGetAllLeagueMatchesResponse = zLeagueMatchPage;

export type GetAllLeagueMatchesResponseZodType = z.infer<typeof zGetAllLeagueMatchesResponse>;

export const zGetLeagueMatchByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLeagueMatchByUuidDataZodType = z.infer<typeof zGetLeagueMatchByUuidData>;

/**
 * Successful operation
 */
export const zGetLeagueMatchByUuidResponse = zLeagueMatchDto;

export type GetLeagueMatchByUuidResponseZodType = z.infer<typeof zGetLeagueMatchByUuidResponse>;

export const zGetAllMatchDaysData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllMatchDaysDataZodType = z.infer<typeof zGetAllMatchDaysData>;

/**
 * Successful operation
 */
export const zGetAllMatchDaysResponse = zLeagueMatchDayPage;

export type GetAllMatchDaysResponseZodType = z.infer<typeof zGetAllMatchDaysResponse>;

export const zGetMatchDayByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchDayByUuidDataZodType = z.infer<typeof zGetMatchDayByUuidData>;

/**
 * Successful operation
 */
export const zGetMatchDayByUuidResponse = zLeagueMatchDayDto;

export type GetMatchDayByUuidResponseZodType = z.infer<typeof zGetMatchDayByUuidResponse>;

export const zGetMatchesByMatchDayData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetMatchesByMatchDayDataZodType = z.infer<typeof zGetMatchesByMatchDayData>;

/**
 * Successful operation
 */
export const zGetMatchesByMatchDayResponse = zLeagueMatchPage;

export type GetMatchesByMatchDayResponseZodType = z.infer<typeof zGetMatchesByMatchDayResponse>;

export const zGetAllSuperCompetitionsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        })),
        season: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for season using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllSuperCompetitionsDataZodType = z.infer<typeof zGetAllSuperCompetitionsData>;

/**
 * Successful operation
 */
export const zGetAllSuperCompetitionsResponse = zSuperCompetitionPage;

export type GetAllSuperCompetitionsResponseZodType = z.infer<typeof zGetAllSuperCompetitionsResponse>;

export const zGetSuperCompetitionByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetSuperCompetitionByUuidDataZodType = z.infer<typeof zGetSuperCompetitionByUuidData>;

/**
 * Successful operation
 */
export const zGetSuperCompetitionByUuidResponse = zSuperCompetitionDto;

export type GetSuperCompetitionByUuidResponseZodType = z.infer<typeof zGetSuperCompetitionByUuidResponse>;

export const zGetAllEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllEventsDataZodType = z.infer<typeof zGetAllEventsData>;

/**
 * Successful operation
 */
export const zGetAllEventsResponse = zEventPage;

export type GetAllEventsResponseZodType = z.infer<typeof zGetAllEventsResponse>;

export const zGetEventByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested event'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetEventByUuidDataZodType = z.infer<typeof zGetEventByUuidData>;

/**
 * Successful operation
 */
export const zGetEventByUuidResponse = zEvent;

export type GetEventByUuidResponseZodType = z.infer<typeof zGetEventByUuidResponse>;

export const zGetEventTypeByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string().register(z.globalRegistry, {
            description: 'UUID of the requested event type'
        })
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetEventTypeByUuidDataZodType = z.infer<typeof zGetEventTypeByUuidData>;

/**
 * Successful operation
 */
export const zGetEventTypeByUuidResponse = zEventType;

export type GetEventTypeByUuidResponseZodType = z.infer<typeof zGetEventTypeByUuidResponse>;

export const zGetEventTypesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetEventTypesDataZodType = z.infer<typeof zGetEventTypesData>;

/**
 * Successful operation
 */
export const zGetEventTypesResponse = zEventType;

export type GetEventTypesResponseZodType = z.infer<typeof zGetEventTypesResponse>;

export const zGetAllSeasonsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllSeasonsDataZodType = z.infer<typeof zGetAllSeasonsData>;

/**
 * Successful operation
 */
export const zGetAllSeasonsResponse = z.array(zSeasonDto).register(z.globalRegistry, {
    description: 'Successful operation'
});

export type GetAllSeasonsResponseZodType = z.infer<typeof zGetAllSeasonsResponse>;

export const zGetLeagueHierarchiesForSeasonData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetLeagueHierarchiesForSeasonDataZodType = z.infer<typeof zGetLeagueHierarchiesForSeasonData>;

/**
 * Successful operation
 */
export const zGetLeagueHierarchiesForSeasonResponse = zLeagueHierarchyPage;

export type GetLeagueHierarchiesForSeasonResponseZodType = z.infer<typeof zGetLeagueHierarchiesForSeasonResponse>;

export const zGetSeasonByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetSeasonByUuidDataZodType = z.infer<typeof zGetSeasonByUuidData>;

/**
 * Successful operation
 */
export const zGetSeasonByUuidResponse = zSeasonDto;

export type GetSeasonByUuidResponseZodType = z.infer<typeof zGetSeasonByUuidResponse>;

export const zGetAllSportsclubsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllSportsclubsDataZodType = z.infer<typeof zGetAllSportsclubsData>;

/**
 * Successful operation
 */
export const zGetAllSportsclubsResponse = zSportsclubPage;

export type GetAllSportsclubsResponseZodType = z.infer<typeof zGetAllSportsclubsResponse>;

export const zGetSportsclubData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetSportsclubDataZodType = z.infer<typeof zGetSportsclubData>;

/**
 * Successful operation
 */
export const zGetSportsclubResponse = zSportsclubDto;

export type GetSportsclubResponseZodType = z.infer<typeof zGetSportsclubResponse>;

export const zGetAllTeamsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested page number. Defaults to the first page (i.e. page number 0).'
        })),
        size: z.optional(z.int().register(z.globalRegistry, {
            description: 'Requested number of items per page. Defaults to 20. The maximum allowed value is 100'
        })),
        association: z.optional(z.string().register(z.globalRegistry, {
            description: 'Filter for association using the given UUID. Defaults to no filtering.'
        }))
    })),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetAllTeamsDataZodType = z.infer<typeof zGetAllTeamsData>;

/**
 * Successful operation
 */
export const zGetAllTeamsResponse = zTeamPage;

export type GetAllTeamsResponseZodType = z.infer<typeof zGetAllTeamsResponse>;

export const zGetTeamByUuidData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        uuid: z.string()
    }),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetTeamByUuidDataZodType = z.infer<typeof zGetTeamByUuidData>;

/**
 * Successful operation
 */
export const zGetTeamByUuidResponse = zTeamDto;

export type GetTeamByUuidResponseZodType = z.infer<typeof zGetTeamByUuidResponse>;

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type GetCurrentUserDataZodType = z.infer<typeof zGetCurrentUserData>;

/**
 * Successful operation
 */
export const zGetCurrentUserResponse = zUserDetailsDto;

export type GetCurrentUserResponseZodType = z.infer<typeof zGetCurrentUserResponse>;

export const zUserDetailsRootLinksData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(z.object({
        'X-Api-Key': z.optional(z.string().register(z.globalRegistry, {
            description: 'A SAMS API key with permission to access this API.'
        }))
    }))
});

export type UserDetailsRootLinksDataZodType = z.infer<typeof zUserDetailsRootLinksData>;

/**
 * Successful operation
 */
export const zUserDetailsRootLinksResponse = zHalRepresentation;

export type UserDetailsRootLinksResponseZodType = z.infer<typeof zUserDetailsRootLinksResponse>;
