name: Combined Calender

concurrency:
  group: "combined-ics"
  cancel-in-progress: false

on:
  push:
    paths:
      - "ics/*.ics"
      - "!ics/all.ics"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  ICS_FOLDER: ics/ # the folder containing all ics files
  ICS_COMBINED_TARGET: ics/all.ics # the target for the merged calendar

jobs:
  Merge-Calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Merge Calendar Files
        id: merge_cal
        run: |
          cat ${{env.ICS_FOLDER}}*.ics > temp1.ics
          cat temp1.ics | grep -v CALNAME | grep -v BEGIN:VCALENDAR | grep -v END:VCALENDAR > temp2.ics
          echo "BEGIN:VCALENDAR" > ${{env.ICS_COMBINED_TARGET}}
          echo "X-WR-CALNAME:Volleyballclub Müllheim" >> ${{env.ICS_COMBINED_TARGET}}
          cat temp2.ics >> ${{env.ICS_COMBINED_TARGET}}
          echo "END:VCALENDAR" >> ${{env.ICS_COMBINED_TARGET}}
        # overwrites the merged calendar file with data from all other ics (presumably)

      - name: Git Add & Push
        id: git_push
        if: steps.merge_cal.outcome == 'success'
        run: |
          git add ${{env.ICS_COMBINED_TARGET}}
          git commit -m "Combined Calender update [skip ci]"
          git push origin --all --quiet -f