name: Combined Matches

concurrency:
  group: "combined-matches"
  cancel-in-progress: false

on:
  push:
    paths:
      - "_sams/xml/matches/*.xml"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  XML_SOURCES: _sams/xml/matches/ # the folder containing all SAMS xml source files
  COMBINED_XML: _sams/xml/combined_matches.xml # the target for the merged xml
  COMBINED_MATCHES: _pages/termine.md # the output file which will be rendered on the page

jobs:
  Merge-Calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Merge Matches Files
        id: merge_matches
        run: |
          cat ${{env.XML_SOURCES}}*.xml > temp1.xml
          cat temp1.xml | grep -v '<?xml' | grep -v '<matches' | grep -v '</matches>' > temp2.xml
          echo '<?xml version="1.0" encoding="UTF-8"?><matches>' > ${{env.COMBINED_XML}}
          cat temp2.xml >> ${{env.COMBINED_XML}}
          echo '</matches>' >> ${{env.COMBINED_XML}}

      - name: XSLT processing (combined matches) # Push the XML through the XSLT
        id: combined_matches_xslt
        if: steps.merge_matches.conclusion == 'success'
        run: |
          sudo apt-get install xsltproc
          xsltproc _sams/xslt/combined_matches.xslt ${{env.COMBINED_XML}} > ${{env.COMBINED_MATCHES}}

      - name: Git Add & Push
        id: git_push
        if: steps.combined_matches_xslt.outcome == 'success'
        run: |
          git add ${{env.COMBINED_XML}}
          git commit -m "XML update [skip ci]"
          git add ${{env.COMBINED_MATCHES}}
          git commit -m "Combined Macthes update [skip ci]"
          git push origin --all --quiet -f