name: NEW Rankings Update

on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  RANKINGS_SOURCE: _sams/xml/rankings
  MATCHES_SOURCE: _sams/xml/matches
  RANKINGS_TARGET: _rankings
  MATCHES_TARGET: _matches

jobs:
  Updated-XML:
    runs-on: ubuntu-latest
    outputs:
      files-updated: ${{ steps.files.outputs.added_modified }} # contains each file modified by the commit who triggered this run
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'json'

  Rankings:
    needs: Updated-XML
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        ids: ${{fromJSON(needs.Updated-XML.outputs.files-updated)}}
    if: contains(matrix.ids, env.RANKINGS_SOURCE) # checks if the file is a ranking file
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Ranking File
        run: |
          mkdir -p ${{ env.RANKINGS_SOURCE }}
          curl -o ${{matrix.teams}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.ids}}"
          echo "${{matrix.ids}}"