name: NEW Rankings Update

on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  RANKINGS_SOURCE: _sams/xml/rankings
  MATCHES_SOURCE: _sams/xml/matches
  RANKINGS_TARGET: _rankings
  MATCHES_TARGET: _matches

jobs:
  Updated-XML:
    runs-on: ubuntu-latest
    outputs:
      rankings: ${{ steps.filter_rankings.outputs.rankings }} # rankings to be processed
      matches: ${{ steps.filter_matches.outputs.matches }} # matches to be processed
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'space-delimited'

      - name: Prepare Directory
        id: mkdir
        run: |
          mkdir -p ${{env.RANKINGS_SOURCE}}
          mkdir -p ${{env.MATCHES_SOURCE}}

      - name: Filter Ranking Files
        id: filter_rankings
        run: |
          for file in ${{steps.files.outputs.added_modified}}
          do
            echo "$file"
            if [[ $file = *_sams/xml/rankings* ]] ; then files_rankings="$file,$files_rankings" ; fi
          done
          echo "rankings=[$files_rankings%?]" >> $GITHUB_OUTPUT

      - name: Filter Matches Files
        id: filter_matches
        run: |
          for file in ${{steps.files.outputs.added_modified}}
          do
            echo "$file"
            if [[ $file = *_sams/xml/matches* ]] ; then files_matches="$file,$files_matches" ; fi
          done
          echo "matches=[$files_matches%?]" >> $GITHUB_OUTPUT

      - name: List files
        run: |
          echo "here are the lists:"
          echo "${{steps.filter_rankings.outputs.rankings}}"
          echo "${{steps.filter_matches.outputs.matches}}"

  Rankings:
    needs: Updated-XML
    continue-on-error: true # if one team fails, the flow should continue
    strategy:
      #max-parallel: 1
      matrix:
        teams: ${{fromJSON(needs.Updated-XML.outputs.rankings)}}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Ranking File
        run: |
          curl -o ${{matrix.teams}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.teams}}"
          echo "${{matrix.teams}}"