name: NEW Rankings & Matches Update

on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  RANKINGS_SOURCE: _sams/xml/rankings/
  MATCHES_SOURCE: _sams/xml/matches/
  RANKINGS_TARGET: _rankings/
  MATCHES_TARGET: _matches/

jobs:

  Identify-Update:
    runs-on: ubuntu-latest
    outputs:
      files-updated: ${{ steps.files.outputs.added_modified }} # contains each file modified by the commit who triggered this run
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'

  ########################
  ### RANKINGS PROCESS ###
  ########################
  Process-Rankings:
    needs: Identify-Update
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        ids: ${{fromJSON(needs.Identify-Update.outputs.files-updated)}}
    outputs:
      upload_required: ${{ steps.upload_status.outputs.required }} # controls the artifact download before commit
    runs-on: ubuntu-latest
    steps:
      - name: Filter & Fetch Rankings
        id: filtered_fetch
        if: contains( matrix.ids, env.RANKINGS_SOURCE )
        # checks if the file is either a ranking or match
        run: |
          mkdir -p ${{env.RANKINGS_SOURCE}}
          curl -o ${{matrix.ids}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.ids}}"
          echo "${{matrix.ids}}"

      - name: Isolate ID # Isolate just the ID from the file (remove path and file extension) and make it available in later steps
        if: steps.filtered_fetch.conclusion == 'success'
        id: isolate_id
        run: |
          id_only=${{matrix.ids}}
          id_only=$(echo $id_only | sed -e 's!\.xml!!')
          id_only=$(echo $id_only | sed -e 's!${{env.RANKINGS_SOURCE}}!!')
          echo $id_only
          echo "id=$id_only" >> $GITHUB_OUTPUT

      - name: Add timestamp to Rankings XML
        # includes a timestamp at the end of the files in the German format to be used in the frontend
        id: timestamp_rankings
        if: contains( matrix.ids, env.RANKINGS_SOURCE )
        run: |
          echo $(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)
          sed -i -e 's!</rankings>!<timestamp>'$(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)' Uhr</timestamp></rankings>!g' ${{matrix.ids}}
        
      - name: Get rankings.xslt template # Get the xslt template
        if: ${{ steps.timestamp_rankings.conclusion == 'success' }}
        id: rankings_xslt_template
        run: curl -o rankings.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xslt/rankings.xslt"

      - name: XSLT processing # Push the XML through the XSLT
        if: steps.rankings_xslt_template.conclusion == 'success'
        id: xslt_rankings
        run: |
          mkdir -p ${{env.RANKINGS_TARGET}}
          targetfile=${{env.RANKINGS_TARGET}}
          targetfile+=${{steps.isolate_id.outputs.id}}
          targetfile+=".html"
          echo $targetfile
          sudo apt-get install xsltproc
          xsltproc rankings.xslt ${{matrix.ids}} > $targetfile

      - name: Upload Artifact
        if: steps.xslt_rankings.conclusion == 'success'
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: rankings
          path: ${{env.RANKINGS_TARGET}}

      - name: Upload Status
        if: steps.upload.conclusion == 'success'
        id: upload_status
        run: echo "required=yes" >> $GITHUB_OUTPUT

  #######################
  ### MATCHES PROCESS ###
  #######################
  Process-Matches:
    needs: Identify-Update
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        ids: ${{fromJSON(needs.Identify-Update.outputs.files-updated)}}
    outputs:
      upload_required: ${{ steps.upload_status.outputs.required }} # controls the artifact download before commit
    runs-on: ubuntu-latest
    steps:
      - name: Filter & Fetch Matches
        id: filtered_fetch
        if: contains( matrix.ids, env.MATCHES_SOURCE )
        # checks if the file is a match
        run: |
          mkdir -p ${{env.MATCHES_SOURCE}}
          curl -o ${{matrix.ids}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.ids}}"
          echo "${{matrix.ids}}"

      - name: Isolate ID # Isolate just the ID from the file (remove path and file extension) and make it available in later steps
        if: steps.filtered_fetch.conclusion == 'success'
        id: isolate_id
        run: |
          id_only=${{matrix.ids}}
          id_only=$(echo $id_only | sed -e 's!\.xml!!')
          id_only=$(echo $id_only | sed -e 's!${{env.MATCHES_SOURCE}}!!')
          echo $id_only
          echo "id=$id_only" >> $GITHUB_OUTPUT

      - name: MATCHES PROCESS
        if: contains( matrix.ids, env.MATCHES_SOURCE )
        run: echo "Lets process matches!"

      - name: Add timestamp to Matches XML
        # includes a timestamp at the end of the files in the German format to be used in the frontend
        id: timestamp_matches
        if: contains( matrix.ids, env.MATCHES_SOURCE )
        run: |
          echo $(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)
          sed -i -e 's!</matches>!<timestamp>'$(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)' Uhr</timestamp></matches>!g' ${{matrix.ids}}

      - name: Upload Artifact
        if: steps.last_step_in_matches_process.conclusion == 'success'
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: matches
          path: ${{ env.MATCHES_TARGET }}

      - name: Upload Status
        if: steps.upload.conclusion == 'success'
        id: upload_status
        run: echo "required=yes" >> $GITHUB_OUTPUT


  #############################
  ### GIT UPDATE PROCESS ###
  #############################
  Git-Update:
    needs: [Process-Rankings, Process-Matches]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{env.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Download Rankings
        if: contains(needs.Process-Rankings.outputs.upload_required, 'yes')
        id: dowload_rankings
        uses: actions/download-artifact@v3
        with:
          name: rankings
          path: ${{ env.RANKINGS_TARGET }}

      - name: Download Matches
        if: contains(needs.Process-Matches.outputs.upload_required, 'yes')
        id: dowload_matches
        uses: actions/download-artifact@v3
        with:
          matches: matches
          path: ${{ env.MATCHES_TARGET }}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit Rankings
        if: steps.dowload_rankings.conclusion == 'success'
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.RANKINGS_TARGET}}"
          git commit -m "rankings update"

      - name: Commit Matching
        if: steps.dowload_matches.conclusion == 'success'
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.MATCHES_TARGET}}"
          git commit -m "matches update"

      - name: Git Push
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git pull --rebase
          git push origin --all --quiet