name: NEW Rankings Update

on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  RANKINGS_SOURCE: _sams/xml/rankings
  MATCHES_SOURCE: _sams/xml/matches
  RANKINGS_TARGET: _rankings
  MATCHES_TARGET: _matches

jobs:
  Updated-XML:
    runs-on: ubuntu-latest
    outputs:
      filenames: ${{ steps.files.outputs.added_modified }} # array of files changed by the commit who triggered the workflow
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'space-delimited'

      - name: Prepare Directory
        id: mkdir
        run: |
          mkdir -p ${{env.RANKINGS_SOURCE}}
          mkdir -p ${{env.MATCHES_SOURCE}}

      - name: Separate Modified Files
        id: separate
        run: |
          for file in ${{steps.files.outputs.added_modified}}
          do
            echo "$file"
            if [[ $file = *_sams/xml/rankings* ]] ; then files_rankings="$files_rankings,$file" ; fi
            if [[ $file = *_sams/xml/matches* ]] ; then files_matches="$files_matches,$file" ; fi
          done
          echo "here are the lists:"
          echo "$files_rankings"
          echo "$files_matches"
          echo "RANKINGS=[$files_rankings]" >> $GITHUB_OUTPUT 
          echo "MATCHES=[$files_matches]" >> $GITHUB_OUTPUT 

  Rankings:
    needs: Updated-XML
    continue-on-error: true # if one team fails, the flow should continue
    strategy:
      #max-parallel: 1
      matrix:
        teams: ${{fromJSON(env.RANKINGS)}}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Ranking File
        run: |
          curl -o ${{matrix.teams}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.teams}}"
          echo "${{matrix.teams}}"