name: NEW Rankings & Matches Update

on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  RANKINGS_SOURCE: _sams/xml/rankings/
  MATCHES_SOURCE: _sams/xml/matches/
  RANKINGS_TARGET: _rankings/
  MATCHES_TARGET: _matches/
  INDIVIDUAL_MATCHES_TARGET: _spielergebnisse/
  ICS_TARGET: ics/

jobs:

  Identify-Update:
    runs-on: ubuntu-latest
    outputs:
      files-updated: ${{ steps.files.outputs.added_modified }} # contains each file modified by the commit who triggered this run
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'

  ########################
  ### RANKINGS PROCESS ###
  ########################
  Process-Rankings:
    needs: Identify-Update
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        ids: ${{fromJSON(needs.Identify-Update.outputs.files-updated)}}
    outputs:
      upload_required: ${{ steps.upload_status.outputs.required }} # controls the artifact download before commit
    runs-on: ubuntu-latest
    steps:
      - name: Filter & Fetch Rankings
        id: filtered_fetch
        if: contains( matrix.ids, env.RANKINGS_SOURCE )
        # checks if the file is either a ranking or match
        run: |
          mkdir -p ${{env.RANKINGS_SOURCE}}
          curl -o ${{matrix.ids}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.ids}}"
          echo "${{matrix.ids}}"

      - name: Isolate ID # Isolate just the ID from the file (remove path and file extension) and make it available in later steps
        id: isolate_id
        if: steps.filtered_fetch.conclusion == 'success'
        run: |
          id_only=${{matrix.ids}}
          id_only=$(echo $id_only | sed -e 's!\.xml!!')
          id_only=$(echo $id_only | sed -e 's!${{env.RANKINGS_SOURCE}}!!')
          echo $id_only
          echo "id=$id_only" >> $GITHUB_OUTPUT

      - name: Add timestamp to Rankings XML
        # includes a timestamp at the end of the files in the German format to be used in the frontend
        id: timestamp_rankings
        if: contains( matrix.ids, env.RANKINGS_SOURCE )
        run: |
          echo $(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)
          sed -i -e 's!</rankings>!<timestamp>'$(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)' Uhr</timestamp></rankings>!g' ${{matrix.ids}}
        
      - name: Get rankings.xslt template # Get the xslt template
        id: get_xslt_template
        if: ${{ steps.timestamp_rankings.conclusion == 'success' }}
        run: curl -o rankings.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xslt/rankings.xslt"

      - name: XSLT processing # Push the XML through the XSLT
        id: xslt_rankings
        if: steps.get_xslt_template.conclusion == 'success'
        run: |
          mkdir -p ${{env.RANKINGS_TARGET}}
          targetfile=${{env.RANKINGS_TARGET}}
          targetfile+=${{steps.isolate_id.outputs.id}}
          targetfile+=".html"
          echo $targetfile
          sudo apt-get install xsltproc
          xsltproc rankings.xslt ${{matrix.ids}} > $targetfile

      - name: Upload Artifact
        id: upload
        if: steps.xslt_rankings.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: rankings
          path: ${{env.RANKINGS_TARGET}}

      - name: Upload Status
        id: upload_status
        if: steps.upload.conclusion == 'success'
        run: echo "required=yes" >> $GITHUB_OUTPUT

  #######################
  ### MATCHES PROCESS ###
  #######################
  Process-Matches:
    needs: Identify-Update
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        ids: ${{fromJSON(needs.Identify-Update.outputs.files-updated)}}
    outputs:
      upload_required: ${{ steps.upload_status.outputs.required }} # controls the artifact download before commit
    runs-on: ubuntu-latest
    steps:
      - name: Filter & Fetch Matches
        id: filtered_fetch
        if: contains( matrix.ids, env.MATCHES_SOURCE )
        # checks if the file is a match
        run: |
          mkdir -p ${{env.MATCHES_SOURCE}}
          curl -o ${{matrix.ids}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.ids}}"
          echo "${{matrix.ids}}"

      - name: Isolate ID # Isolate just the ID from the file (remove path and file extension) and make it available in later steps
        id: isolate_id
        if: steps.filtered_fetch.conclusion == 'success'
        run: |
          id_only=${{matrix.ids}}
          id_only=$(echo $id_only | sed -e 's!\.xml!!')
          id_only=$(echo $id_only | sed -e 's!${{env.MATCHES_SOURCE}}!!')
          echo $id_only
          echo "id=$id_only" >> $GITHUB_OUTPUT

      - name: Add timestamp to Matches XML
        # includes a timestamp at the end of the files in the German format to be used in the frontend
        id: timestamp_matches
        if: contains( matrix.ids, env.MATCHES_SOURCE )
        run: |
          echo $(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)
          sed -i -e 's!</matches>!<timestamp>'$(TZ=Europe/Berlin date +%d.%m.%Y)', '$(TZ=Europe/Berlin date +%H:%M)' Uhr</timestamp></matches>!g' ${{matrix.ids}}

      - name: Cleanup SAMS XML # removes strings that break the XLST
        id: cleanup_xml
        if: steps.timestamp_matches.conclusion == 'success'
        run: sed -i -e 's!xmlns="http://sams-server.de/api/xml/ns/matches" !!g' ${{matrix.ids}}

      - name: Get XSLT templates # Download the templates from our repo
        id: get_xslt_template
        if: steps.cleanup_xml.conclusion == 'success'
        run: |
          curl -o matches.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xslt/matches.xslt"
          curl -o individual_matches.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xslt/individual_matches.xslt"

      - name: XSLT processing (matches) # Push the XML through the XSLT
        id: matches_xslt
        if: steps.cleanup_xml.conclusion == 'success'
        run: |
          mkdir -p ${{env.MATCHES_TARGET}}
          targetfile=${{env.MATCHES_TARGET}}
          targetfile+=${{steps.isolate_id.outputs.id}}
          targetfile+=".html"
          echo $targetfile
          sudo apt-get install xsltproc
          xsltproc matches.xslt ${{matrix.ids}} > $targetfile

      ### handle calender file caching ###
      - name: Import & Modify iCal # Import the iCal file so we can cache it
        # this downlodas the ical file from SAMS, saves it as ics then adds "team name + VC Müllheim Spielplan" as calender name to it
        # the modification is a beautification of the calendar file only and does not affect functionality
        id: samsical
        if: steps.matches_xslt.outcome == 'success'
        continue-on-error: true
        run: |
          processed_match_file=${{env.MATCHES_TARGET}}
          processed_match_file+=${{steps.isolate_id.outputs.id}}
          processed_match_file+=".html"
          ics_target_file=${{env.ICS_TARGET}}
          ics_target_file+=${{steps.isolate_id.outputs.id}}
          ics_target_file+=".ics"
          echo $processed_match_file" is used to modify "$ics_target_file" (Team and Club name)"
          mkdir -p ${{env.ICS_TARGET}}
          curl -o $ics_target_file "https://www.sbvv-online.de/iCal/team/matches.ical?teamId=${{steps.isolate_id.outputs.id}}"
          teamname=$(awk "/title: (.*) \(Saison/{print}" $processed_match_file | sed 's!title: !!' | sed 's! (Saison.*!!')
          echo $teamname
          sed -i -e "s!BEGIN:VCALENDAR!BEGIN:VCALENDAR\nX-WR-CALNAME:$teamname (VC Müllheim)!g" $ics_target_file

      - name: Patch Calender URL in Match file
      # Replaces the placeholderlinks in the Match file with the actual .ics file
      # Then removes the display-none class to enable them in the frontend
        if: steps.samsical.outcome == 'success'
        run: |
          processed_match_file=${{env.MATCHES_TARGET}}
          processed_match_file+=${{steps.isolate_id.outputs.id}}
          processed_match_file+=".html"
          ics_target_file=${{env.ICS_TARGET}}
          ics_target_file+=${{steps.isolate_id.outputs.id}}
          ics_target_file+=".ics"
          echo $processed_match_file" will be updated to link to "$ics_target_file
          sed -i -e "s!CALURL1!https://vcmuellheim.de/$ics_target_file!g" $processed_match_file
          sed -i -e "s!CALURL2!webcal://vcmuellheim.de/$ics_target_file!g" $processed_match_file
          sed -i -e "s!calendar d-none!calendar!g" $processed_match_file

      - name: Upload Artifact (Matches)
        id: upload
        if: steps.matches_xslt.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: matches
          path: ${{ env.MATCHES_TARGET }}

      - name: Upload Status
        id: upload_status
        if: steps.upload.conclusion == 'success'
        run: echo "required=yes" >> $GITHUB_OUTPUT

      ### individual matches ###
      - name: XSLT processing (individual matches) # Download, install and run the XSLT processor (Saxon to use XSLT 2.0 features)
        id: individual_matches_xslt
        if: steps.matches_xslt.conclusion == 'success'
        run: |
          git clone https://github.com/sputnick-dev/saxon-lint.git
          cd saxon-lint*
          chmod +x saxon-lint.pl
          ./saxon-lint.pl --help
          cd ..
          mkdir -p ${{env.INDIVIDUAL_MATCHES_TARGET}}
          ./saxon-lint/saxon-lint.pl --xslt individual_matches.xslt ${{matrix.ids}}
        # the saxon output file & location is declared in the xslt file, not by this command!

      - name: Upload Artifact (Individual Matches)
        id: upload_individual_matches
        if: steps.individual_matches_xslt.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: individual_matches
          path: ${{env.INDIVIDUAL_MATCHES_TARGET}}

      - name: Upload Artifact (Calender Files)
        id: upload_ics_files
        if: steps.samsical.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: individual_matches
          path: ${{env.ICS_TARGET}}

  ##########################
  ### GIT UPDATE PROCESS ###
  ##########################
  Git-Update:
    needs:
      - Process-Rankings
      - Process-Matches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{env.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Download Rankings
        id: dowload_rankings
        if: contains(needs.Process-Rankings.outputs.upload_required, 'yes')
        uses: actions/download-artifact@v3
        with:
          name: rankings
          path: ${{ env.RANKINGS_TARGET }}

      - name: Download Matches
        id: dowload_matches
        if: contains(needs.Process-Matches.outputs.upload_required, 'yes')
        uses: actions/download-artifact@v3
        with:
          name: matches
          path: ${{ env.MATCHES_TARGET }}

      - name: Download Individual Matches
        id: dowload_individual_matches
        if: contains(needs.Process-Matches.outputs.upload_required, 'yes')
        uses: actions/download-artifact@v3
        with:
          name: individual_matches
          path: ${{env.INDIVIDUAL_MATCHES_TARGET}}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit Rankings
        if: steps.dowload_rankings.conclusion == 'success'
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.RANKINGS_TARGET}}"
          git commit -m "rankings update"

      - name: Commit Matching
        if: steps.dowload_matches.conclusion == 'success'
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.MATCHES_TARGET}}"
          git commit -m "matches update"

      - name: Commit Individual Matching
        if: steps.dowload_individual_matches.conclusion == 'success'
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.INDIVIDUAL_MATCHES_TARGET}}"
          git commit -m "individual matches update"

      - name: Git Push
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git pull --rebase
          git push origin --all --quiet