name: Inbox to Blog Post

on:
  push:
    branches:
      - "main"
    paths:
      - "_inbox/**"
      - "!_posts/**"
      - "!data/posts/**"
      - "!images/**"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  INPUT_FOLDER: _inbox ## the folder to drop into github
  TARGET_FOLDER: data/posts ## the target path for nextJS
  IMAGES_FOLDER: public/images/blog ## the target path for nextJS
  IMAGES_META_FOLDER: images/blog ## the target path for nextJS

jobs:
  build:
    name: Document & Image Processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{env.GITHUB_TOKEN}}
          fetch-depth: 1

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Scan Inbox
        id: scan_inbox
        run: |
          for file in ${{ env.INPUT_FOLDER }}/*
          do
              if [[ $file == *.doc ]] || [[ $file == *.docx ]] || [[ $file == *.rtf ]] || [[ $file == *.txt ]] || [[ $file == *.odt ]]; then
                  title=$(basename "${file%.*}")
                  slug=$(echo "$title" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
                  target=${{ env.TARGET_FOLDER }}/$(date -u +%F)-$slug.md
                  imagesFolder=${{ env.IMAGES_FOLDER }}/$(date -u +%Y/%m/%d)
                  imagesMetaFolder=${{ env.IMAGES_META_FOLDER }}/$(date -u +%Y/%m/%d)
                  echo "DOC_FILE=$file" >> "$GITHUB_OUTPUT"
                  echo "DOC_TITLE=$title" >> "$GITHUB_OUTPUT"
                  echo "DOC_SLUG=$slug" >> "$GITHUB_OUTPUT"
                  echo "MD_TARGET=$target" >> "$GITHUB_OUTPUT"
                  echo "IMAGES_FOLDER=$imagesFolder" >> "$GITHUB_OUTPUT"
                  echo "IMAGES_META_FOLDER=$imagesMetaFolder" >> "$GITHUB_OUTPUT"
                  echo "FILE: $file"
                  echo "TITLE: $title"
                  echo "SLUG: $slug"
                  echo "TARGET: $target"
                  echo "IMAGES: $imagesFolder"
              fi
          done

      - name: Convert to Markdown
        id: pandoc
        if: ${{ steps.scan_inbox.outputs.MD_TARGET != 0 }}
        uses: docker://pandoc/core:3.1.1
        with:
          args: --to gfm --output="${{steps.scan_inbox.outputs.MD_TARGET}}" "${{steps.scan_inbox.outputs.DOC_FILE}}"

      - name: Debug File
        if: steps.pandoc.conclusion == 'success'
        run: |
          cat ${{steps.scan_inbox.outputs.MD_TARGET}}

      - name: Add Front Matter
        if: steps.pandoc.conclusion == 'success'
        run: |
          sed -i "1s|.*|---\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"
          sed -i "2s|.*|layout: post\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"
          sed -i "3s|.*|title: ${{steps.scan_inbox.outputs.DOC_TITLE}}\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"
          sed -i "4s|.*|date: $(date -u +%Y-%m-%dT%H:%M:%SZ)\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"
          sed -i "5s|.*|---\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"

      - name: Process Images
        if: steps.pandoc.conclusion == 'success'
        run: |
          unset imageCount
          for image in ${{ env.INPUT_FOLDER }}/*.[Jj]*[Pp][Gg]
          do
              if [[ -z $imageCount ]]; then
                mkdir -p ${{steps.scan_inbox.outputs.IMAGES_FOLDER}}
                sed -i "5s|.*|gallery:\n&|" "${{steps.scan_inbox.outputs.MD_TARGET}}"
              fi
              imageCount=$((imageCount+1))
              imageTarget=${{steps.scan_inbox.outputs.IMAGES_FOLDER}}/$(basename $image)
              imageMetaTarget=${{steps.scan_inbox.outputs.IMAGES_META_FOLDER}}/$(basename $image)
              imageTarget=$(echo $imageTarget | tr '[:upper:]' '[:lower:]' | sed 's/.jpeg/.jpg/g' | sed 's/img-//g')
              imageMetaTarget=$(echo $imageMetaTarget | tr '[:upper:]' '[:lower:]' | sed 's/.jpeg/.jpg/g' | sed 's/img-//g')
              convert $image -resize '1920x1920>' $imageTarget
              sed -i "$((imageCount+5))s|.*|- /$imageMetaTarget\n&|" '${{steps.scan_inbox.outputs.MD_TARGET}}'
          done

      - name: Clean Inbox
        if: steps.pandoc.conclusion == 'success'
        id: cleanInbox
        run: |
          for all in ${{ env.INPUT_FOLDER }}/*
          do
              mkdir -p "_processed"
              mv "$all" "_processed"
          done
          echo "The following files have been removed from the inbox:"
          ls _processed

      - name: Git Push
        if: steps.pandoc.conclusion == 'success'
        run: |
          git add ${{ env.INPUT_FOLDER }}
          git commit -m "purge inbox [skip ci]"
          git pull --quiet --rebase
          git push origin --all --quiet -f
          git add ${{steps.scan_inbox.outputs.MD_TARGET}}
          git add ${{steps.scan_inbox.outputs.IMAGES_FOLDER}}
          git commit -m "new post from inbox"
          git pull --quiet --rebase
          git push origin --all --quiet -f
