name: SAMS Match Schedule

on:
  schedule:
  - cron: 33 6 * * * # every night
  - cron: 0 10-22 * * 0,6 # every hour on sa & sun between 10AM - 10PM
  workflow_dispatch:
  
env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: https://www.volleyball-baden.de
  SAMS_TEAMIDS: "[18452008, 18450973, 18450721, 19046138]" #herren1 herren2 damen1 damen2
  REPO_TARGET: sams/matches


jobs:
  Get-Teams:
    runs-on: ubuntu-latest
    steps:
      - name: Get XML
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'sams/club.xml'
          xpath: '/sportsclub/teams/team/seasonTeamId'
        
      - name: Log Team IDs
        id: teamsarray
        run: echo "::set-output name=teamids::[${{ steps.getxml.outputs.info }}]"


  Fetch-to-XML:
    needs: Get-Teams
    strategy:
      matrix:
        teams: ${{ jobs.Get-Teams.steps.teamsarray.outputs.teamids }}
        time: [past, future]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch from SAMS
        run: |
          mkdir -p ${{env.REPO_TARGET}}/${{matrix.time}}
          curl -o ${{env.REPO_TARGET}}/${{matrix.time}}/${{matrix.teams}}.xml "$SAMS_URL/xml/matches.xhtml?apiKey=$SAMS_KEY&${{matrix.time}}=true&teamId=${{matrix.teams}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: matches
          path: ${{env.REPO_TARGET}}


  Git-Update:
    needs: Fetch-to-XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: matches
          path: ${{env.REPO_TARGET}}
          
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Git Commit
        continue-on-error: true # don't throw an error as there won't always be changes compared to the existing file
        run: |
          git add "${{env.REPO_TARGET}}/*"
          git commit -m "sams scheduled update"
          git push origin --all --quiet
