name: SAMS Match Schedule

on:
  schedule:
  - cron: 33 6 * * 3
  workflow_dispatch:
  
env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: "https://www.volleyball-baden.de"
  SAMS_TEAMID: "18452008"


jobs:
  SAMS_Sync_and_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: terijaki/sams/.github/workflows/action.yml@main
        with:
          server_url: $SAMS_URL
          api_key: $SAMS_KEY
          team_id: $SAMS_TEAMID
