name: SAMS XML to JSON

concurrency:
  group: "sams to json"
  cancel-in-progress: false
on:
  push:
    paths:
      - "_sams/xml/rankings/**"
      - "_sams/xml/matches/**"
      - "_sams/xml/club.xml"

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  TARGET_FOLDER: _data/

jobs:

  Identify-Update:
    runs-on: ubuntu-latest
    outputs:
      files-updated: ${{ steps.files.outputs.added_modified }} # contains each file modified by the commit who triggered this run
    steps:
      - name: Identify Modified Files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'

  Process-Rankings:
    needs: Identify-Update
    continue-on-error: true # if one update fails, the flow should continue
    strategy:
      matrix:
        file: ${{fromJSON(needs.Identify-Update.outputs.files-updated)}}
    runs-on: ubuntu-latest
    steps:
      - name: Load File
        id: load_file
        run: |
          curl -o ${{matrix.file}} "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/${{matrix.file}}"
          ls

      - name: Convert XML to JSON
        uses: fabasoad/data-format-converter-action@main
        id: xml_to_json
        if: steps.load_file.conclusion == 'success'
        with:
          input: '${{matrix.file}}'
          from: 'xml'
          to: 'json'
    
      - name: Store JSON
        id: store_json
        if: steps.xml_to_json.conclusion == 'success'
        run: |
            filename=${{matrix.file}}
            filename=$(echo $filename | sed -e 's!\.xml!!')
            filename=$(echo $filename | sed -e 's!\_sams\/xml!${{env.TARGET_FOLDER}}!')
            ${{ steps.xml_to_json.outputs.output }} > $filename
    
      - name: Upload Artifact (JSON)
        id: upload_json
        if: steps.store_json.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: _data
          path: ${{env.TARGET_FOLDER}}
