name: SAMS Club Data Sync

on:
  schedule:
  - cron: "33 6 * * 3"
  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: "https://www.volleyball-baden.de"
  SAMS_CLUBID: "471"


jobs:
  SAMS_Sync_and_Push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Club Data
        run: |
          mkdir sams
          curl -o sams/club.xml "$SAMS_URL/xml/sportsclub.xhtml?apiKey=$SAMS_KEY&sportsclubId=$SAMS_CLUBID"

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Git Commit
        run: |
          git add "sams/club.xml"
          git commit -m "sams scheduled update"
          git push origin --all
