name: SAMS Club Data Sync

on:
  schedule:
  - cron: "33 6 * * 3"
  workflow_dispatch:
  
env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: "https://www.volleyball-baden.de"
  SAMS_CLUBID: "471"


jobs:
  SAMS_Club-Sync:
    runs-on: ubuntu-latest
    steps:

      - name: fetch club data
        run: |
          mkdir sams
          curl -o sams/club.xml "$SAMS_URL/xml/sportsclub.xhtml?apiKey=$SAMS_KEY&sportsclubId=$SAMS_CLUBID"

      - name: publish export artifact
        uses: actions/upload-artifact@v3
        with:
          name: sams
          path: sams

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: git commit
        run: |
          git add "sams/club.xml"
          git commit -m "sams scheduled update"
          git push origin --all
