name: Upcoming Home Games

on:
  workflow_dispatch:
  schedule:
    - cron: 44 22 * * * # every night at 22:44

env:
  SAMS_KEY: ${{ secrets.SAMS_API }} # SAMS API key
  SAMS_URL: https://www.volleyball-baden.de # start of the api http structure
  REPO_TARGET: _heimspiele # the output folder for the home games


jobs:
  Update-Upcoming-Home-Games:
    runs-on: macos-latest
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Query SAMS for Matches in 14 days
        run: |
          today=$(date +%Y-%m-%d)
          in14days=$(date -v+14d +%Y-%m-%d)
          curl -o temp_matches14days.xml "$SAMS_URL/xml/matches.xhtml?apiKey=$SAMS_KEY&after=$today&before=$in14days"

      - name: Upload Artifact (SAMS XML) # not needed, only to keep for troubleshooting
        uses: actions/upload-artifact@v3
        with:
          name: raw_sams_xml
          path: temp_matches14days.xml

      - name: Cleanup SAMS XML # removes strings that break the XLST
        run: sed -i -e 's!xmlns="http://sams-server.de/api/xml/ns/matches" !!g' temp_matches14days.xml

      - name: Reset existing home matches # Deleting existing matches to remove past games from the repo.
        run: |
          rm -rf ${{env.REPO_TARGET}}
          mkdir -p ${{env.REPO_TARGET}}

      - name: XSLT processing (individual matches) # Download, install and run the XSLT processor (Saxon to use XSLT 2.0 features)
        run: |
          git clone https://github.com/sputnick-dev/saxon-lint.git
          cd saxon-lint*
          chmod +x saxon-lint.pl
          ./saxon-lint.pl --help
          cd ..
          cp sams/homegames.xslt homegames.xslt
          ./saxon-lint/saxon-lint.pl --xslt homegames.xslt temp_matches14days.xml

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git pull
          git add "${{env.REPO_TARGET}}/*"
          git commit -m "sams scheduled update"
          git push origin --all --quiet