name: SAMS RAW Data Sync

concurrency:
  group: sams
  cancel-in-progress: false

on:
  schedule:
    - cron: "11 2 * 1-5,9-12 3" # every wednesday night at 2:11 between september - mai
    - cron: "11 2 * 7-8 *" # every night at 2:11 in june and august (more common for changes to occur)
  workflow_dispatch:

env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: "https://www.volleyball-baden.de"
  SAMS_CLUBID: "471"

jobs:
  SAMS_Sync_and_Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Query SAMS for Club Data
        run: |
          mkdir -p _sams/xml
          curl -o _sams/xml/club.xml "$SAMS_URL/xml/sportsclub.xhtml?apiKey=$SAMS_KEY&sportsclubId=$SAMS_CLUBID"

      - name: Upload Artifact (SAMS XML) # not needed, only to keep for troubleshooting
        uses: actions/upload-artifact@v3
        with:
          name: raw_sams_xml
          path: _sams/xml

      - name: Get XML # this reads the XML file and extracts the team IDs
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "_sams/xml/club.xml"
          xpath: "/sportsclub/teams/team/seasonTeamId"

      - name: List Team IDs # displays the team IDs to the console log
        run: echo 'Teams:${{ steps.getxml.outputs.info }}'

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit
        continue-on-error: true # don't throw an error as there won't always be changes compared to the existing file
        run: |
          git add "_sams/xml"
          git commit -m "sams raw update"
          git pull --rebase --quiet
          git push origin --all --quiet
