name: SAMS Match Schedule

on:
  schedule:
  - cron: 33 6 * * *
  workflow_dispatch:
  
env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: https://www.volleyball-baden.de
  SAMS_TEAMIDS: "[18452008, 18450973, 18450721, 19046138]" #herren1 herren2 damen1 damen2
  GIT_PATH: sams/matches


jobs:
  Fetch-to-XML:
    strategy:
      matrix:
        teams: [18452008, 18450973, 18450721, 19046138] #herren1 herren2 damen1 damen2
        time: [past, future]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Fetch from SAMS
        run: |
          mkdir -p $GIT_PATH/${{matrix.time}}
          curl -o $GIT_PATH/${{matrix.time}}/${{matrix.teams}}.xml "$SAMS_URL/xml/matches.xhtml?apiKey=$SAMS_KEY&${{matrix.time}}=true&teamId=${{matrix.teams}}"

      - name: XSLT
        continue-on-error: true
        run: | 
          sudo apt-get install alien dpkg-dev debhelper build-essential
          sudo alien -i libxml2-2.6.27-1.i386.rpm
          xsltproc -version
          xsltproc 'sams/matches.xslt' '$GIT_PATH/${{matrix.time}}/${{matrix.teams}}.xml' > $GIT_PATH/${{matrix.time}}/${{matrix.teams}}.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: matches
          path: $GIT_PATH


  Git:
    needs: Fetch-to-XML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: matches
          path: $GIT_PATH
          
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Git Commit
        continue-on-error: true # don't throw an error as there won't always be changes compared to the existing file
        run: |
          git add "$GIT_PATH/*"
          git commit -m "sams scheduled update"
          git push origin --all --quiet
