name: SAMS RAW Data Sync

concurrency:
  group: sams
  cancel-in-progress: false

on:
  schedule:
    - cron: "3,18,33,48 11-23 * * 6-7" # Every 15 minutes, between 11 AM and 11 PM, Saturday through Sunday
    - cron: "4 4 * * *" # At 04:04 AM
  workflow_dispatch:

env:
  SAMS_KEY: ${{ secrets.SAMS_API }}
  SAMS_URL: "https://www.volleyball-baden.de"
  SAMS_RANKING_TARGET: _sams/xml/rankings # the folder I want the ranking xml files to go to
  SAMS_MATCHES_TARGET: _sams/xml/matches # the folder I want the match xml files to go to
  SAMS_CLUBID: "471"

jobs:
  # get the latest club data first 
  Get-Teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Query SAMS for Club Data
        run: |
          mkdir -p _sams/xml
          curl -o _sams/xml/club.xml "$SAMS_URL/xml/sportsclub.xhtml?apiKey=$SAMS_KEY&sportsclubId=$SAMS_CLUBID"

      - name: Get XML # this reads the XML file and extracts the team IDs
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "_sams/xml/club.xml"
          xpath: "/sportsclub/teams/team/seasonTeamId"

      - name: List Team IDs # displays the team IDs to the console log
        run: echo 'Teams:${{ steps.getxml.outputs.info }}'

      - name: Transform MatchSeries IDs
        id: teamid-list
        run: echo "teamids=[${{steps.teamids-from-club.outputs.info}}]" >> $GITHUB_OUTPUT # transform IDs from "123,456,789" to "[123,456,789]"

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit
        continue-on-error: true # don't throw an error as there won't always be changes compared to the existing file
        run: |
          git add "_sams/xml"
          git commit -m "sams raw club update"
          git pull --rebase --quiet
          git push origin --all --quiet

  # get rankings for every team
  Get-Rankings:
    needs: Get-Teams
    continue-on-error: true # if one team fails, the flow should continue
    strategy:
      #max-parallel: 1
      matrix:
        teams: ${{fromJSON(needs.Get-Teams.outputs.teamids)}}
    runs-on: ubuntu-latest
    steps:
      - name: Get club.xml cache # Get the catched club.xml
        run: curl -o club.xml "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xml/club.xml"

      - name: Get matchSeries IDs from club.xml
        id: matchseriesid-from-club
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "club.xml"
          xpath: "/sportsclub/teams/team[id='${{matrix.teams}}']/matchSeries/id" #extract the matchSeries ID for this team from the XML

      - name: Get rankings.xslt template # Get the xslt template
        run: curl -o rankings.xslt "https://raw.githubusercontent.com/terijaki/vcmuellheim/main/_sams/xslt/rankings.xslt"

      - name: Query SAMS # make the API call to the SAMS server and save it as XML
        run: |
          mkdir -p ${{env.SAMS_RANKING_TARGET}}
          curl -o ${{env.SAMS_RANKING_TARGET}}/${{matrix.teams}}.xml "$SAMS_URL/xml/rankings.xhtml?apiKey=$SAMS_KEY&matchSeriesId=${{steps.matchseriesid-from-club.outputs.info}}"

      - name: Upload Artifact (SAMS XML) # not needed, only to keep for troubleshooting
        uses: actions/upload-artifact@v3
        with:
          name: raw_sams_rankings_xml
          path: ${{env.SAMS_RANKING_TARGET}}/${{matrix.teams}}.xml




  Git-Update-Rankings-and-Matches:
    needs: Get-Rankings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: raw_sams_rankings_xml
          path: ${{env.SAMS_RANKING_TARGET}}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit Rankings
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git add "${{env.SAMS_RANKING_TARGET}}/*"
          git commit -m "sams rankings update"

      - name: Git Push
        continue-on-error: true # don't throw an error as there won't always be changes
        run: |
          git pull --rebase
          git push origin --all --quiet