name: Verify Team IDs

concurrency:
  group: "sams"
  cancel-in-progress: false

on:
  push:
    paths:
      - "_sams/xml/club.xml"
  workflow_dispatch:

env:
  SAMS_CLUB_FILE: _sams/xml/club.xml # the file containing the current team IDs
  TEAMS_FOLDER: _teams/ # the folder containing the teams on our website

jobs:
  Verify-Teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check Team still exists
        id: check-teams
        run: |
          for team in $(ls $TEAMS_FOLDER)
            do
              this_team_id=$(grep -e "sbvv_id" "$TEAMS_FOLDER$team" | sed 's/[^0-9]*//g')

              if [[ "$this_team_id" -gt 3 ]]; then

                check_club=$(grep -e $this_team_id $SAMS_CLUB_FILE)
                check_existence=${#check_club}

                if [[ -z "$check_club" ]]; then
                  echo "$team ($this_team_id) no longer present in club.xml!"
                else
                  echo "$team ($this_team_id) still present in club.xml"
                fi

              fi
            done

#      - uses: nashmaniac/create-issue-action@v1.1
#        name: Create Issue Action
#        with:
#          title: Team ID removed from club.xml
#          token: ${{secrets.GITHUB_TOKEN}}
#          body: Workflow failed for commit ${{github.sha}}