name: Verify Team IDs

concurrency:
  group: "teams-check"
  cancel-in-progress: false

on:
  # push:
  #   paths:
  #     - "_sams/xml/club.xml"
  #     - ".github/workflows/teams_check.yml"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BK_GH_PAT }}
  SAMS_CLUB_FILE: _sams/xml/club.xml # the file containing the current team IDs
  TEAMS_FOLDER: _teams/ # the folder containing the teams on our website

jobs:
  Verify-Teams:
    runs-on: ubuntu-latest
    outputs:
      outdated-teams: ${{ steps.check-teams.outputs.outdated }} # receives the outdated team info
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check Team still exists
        id: check-teams
        continue-on-error: true
        run: |
          echo "Starting process to check if any team's SBVV ID needs attention..."
          for team in $(ls $TEAMS_FOLDER)
            do
              this_team_id=$(grep -e "sbvv_id" "$TEAMS_FOLDER$team" | sed 's/[^0-9]*//g')
              if [[ -z "$this_team_id" ]]; then
                echo "ℹ️ $team contains no SBVV ID"
              else
                if grep -q "$this_team_id" "$SAMS_CLUB_FILE"; then
                  echo "✅ $team ($this_team_id) still present in club.xml"
                else
                  echo "⛔️ $team ($this_team_id) no longer present in club.xml"
                  outdated+=($team#$this_team_id)
                fi
              fi
            done
          if [[ -n "$outdated" ]]; then
            outdated=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${outdated[@]}")
          else
            outdated+=\"none\"
          fi
          echo "outdated=$outdated" >> $GITHUB_OUTPUT
          echo $outdated
        # loop through files in the teams folder and check for sbvv_id
        # for every Id found, check if the ID is still present in the SAMS club.xml
        # when the ID is no longer present, add it to an array
        # the array is then converted from bash array to JSON array, which serves as a matrix for the follow up job

  Create-Issue:
    needs: Verify-Teams
    if: contains(fromJSON(needs.Verify-Teams.outputs.outdated-teams), 'none') == false
    continue-on-error: true # if issue cretion fails, the others should continue
    strategy:
      max-parallel: 1
      matrix:
        team:
          - ${{fromJSON(needs.Verify-Teams.outputs.outdated-teams)}}
    runs-on: ubuntu-latest
    steps:
      - name: Log & Separate Data
        id: log
        run: |
          team_name=$(cut -d '#' -f1 <<< "${{matrix.team}}")
          sams_id=$(cut -d '#' -f2 <<< "${{matrix.team}}")
          echo "The Team ID ($sams_id) stored in $team_name is no longer present in SAMS!"
          echo "team_name=$team_name" >> $GITHUB_OUTPUT
          echo "sams_id=$sams_id" >> $GITHUB_OUTPUT
        # splits the Team Name (e.g. herren1.md) and SAMS ID (e.g 123456)
        # stores values separately to be used dynamically in issue creation title and body

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          token: ${{env.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Remove Outdated ID
        id: remove_id
        run: |
          cd $TEAMS_FOLDER
          sed -i -e "s!${{steps.log.outputs.sams_id}}!null!g" ${{steps.log.outputs.team_name}}
        # remove the ID from the file

      - name: Git Add & Push
        id: git_push
        if: steps.remove_id.outcome == 'success'
        run: |
          git add $TEAMS_FOLDER
          git commit -m "SBVV ID outdated"
          git pull --quiet --rebase
          git push origin --all --quiet -f

      - uses: dacbd/create-issue-action@main
        name: Create Issue Action
        if: steps.git_push.outcome == 'success'
        with:
          token: ${{ github.token }}
          title: Team ID in ${{steps.log.outputs.team_name}} is outdated
          body: The SAMS ID (${{steps.log.outputs.sams_id}}) stored in ${{steps.log.outputs.team_name}} could not be found in club.xml and may need to be updated. ${{github.sha}} See https://www.sbvv-online.de/cms/startseite/verband/ueber_uns/vereine.xhtml?c4302050.view=teams&c4302050.club=471&c4302050.type=list
        # Create an issue referencing the ID removal. This serves as a todo task to get the new SBVV ID manually from their portal.
