name: NEW Thumbnails

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/thumbnails.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy Upload to Thumbnails
        run: |
          ls
          cp -r ./upload/* ./thumbnails
          ls
      - name: Resize Images
        id: resize-images
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          IMAGES_MAX_WIDTH: "620"
          IMAGES_QUALITY: "65"
          IMAGES_FORMATS: "jpg, jpge, png" 
          IMAGES_DIRECTORIES: "thumbnails"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: thumbnails
          path: thumbnails