name: NEW Thumbnails

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/thumbnails.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Upload to Thumbnails
        run: cp -r upload thumbnails

      # Install ImageMagick
      - run: sudo apt-get install -y libfuse2
      - uses: mfinelli/setup-imagemagick@latest

      - run: for thumbnail in thumbnails ; do magick $thumbnail -resize 640x640 $thumbnail ; done
        

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: thumbnails
          path: thumbnails